import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const newCharacters = [
  // 观世音菩萨化身 (33 观音)
  { name: '圣观音', sanskritName: 'Avalokiteśvara', otherNames: ['正观音'], category: '菩萨', summary: '观世音菩萨的标准相。', story: '圣观音是观世音菩萨的标准形象，是最常见的观音相。', scripture: '《法华经》', isHot: false },
  { name: '千手观音', sanskritName: 'Sahasrabhuja-avalokiteśvara', otherNames: ['千手千眼观音', '大悲观音'], category: '菩萨', summary: '具有千手千眼的观音化身。', story: '千手观音是观世音菩萨的化身，象征无限的慈悲与智慧。', scripture: '《千手千眼观世音菩萨广大圆满无碍大悲心陀罗尼经》', isHot: true },
  { name: '十一面观音', sanskritName: 'Ekādaśamu-kha', otherNames: ['十一面观世音'], category: '菩萨', summary: '具有十一张面孔的观音。', story: '十一面观音共有十一张面孔，表法十一地菩萨。', scripture: '《十一面神咒经》', isHot: false },
  { name: '如意轮观音', sanskritName: 'Cintāmaṇicakra', otherNames: ['如意轮菩萨'], category: '菩萨', summary: '能满众生愿望的观音。', story: '如意轮观音以如意宝珠和法轮能满足众生一切愿求。', scripture: '《如意轮陀罗尼经》', isHot: false },
  { name: '不空羂索观音', sanskritName: 'Amoghapāśa', otherNames: ['不空羂索菩萨'], category: '菩萨', summary: '以羂索救度众生的观音。', story: '不空羂索观音以法器羂索救度一切众生。', scripture: '《不空羂索神变真言经》', isHot: false },
  { name: '马头观音', sanskritName: 'Hayagrīva', otherNames: ['马头明王'], category: '菩萨', summary: '观音的愤怒化身。', story: '马头观音以马头为饰，降伏一切魔障。', scripture: '《马头观音心咒经》', isHot: false },
  { name: '准提观音', sanskritName: 'Cundī', otherNames: ['准提佛母'], category: '菩萨', summary: '密教重要本尊。', story: '准提观音感应强力，能息灾增益。', scripture: '《准提陀罗尼经》', isHot: false },
  { name: '杨柳观音', sanskritName: 'Avalokiteśvara-Willow', otherNames: ['杨柳枝观音'], category: '菩萨', summary: '手持杨柳枝的观音。', story: '杨柳观音以杨柳枝消灾解厄。', scripture: '《观音感应传》', isHot: false },
  { name: '白衣观音', sanskritName: 'Avalokiteśvara-White', otherNames: ['白衣观世音'], category: '菩萨', summary: '身着白衣的观音。', story: '白衣观音象征清净无染。', scripture: '《观音感应传》', isHot: false },
  { name: '莲卧观音', sanskritName: 'Avalokiteśvara-Reclining', otherNames: ['卧观音'], category: '菩萨', summary: '以卧姿显现的观音。', story: '莲卧观音以吉祥卧的姿态安卧于莲华之上。', scripture: '《观音感应传》', isHot: false },
  { name: '泷见观音', sanskritName: 'Avalokiteśvara-Waterfall', otherNames: ['瀑布观音'], category: '菩萨', summary: '在瀑布前显现的观音。', story: '泷见观音观照瀑布，如观心念。', scripture: '《观音感应传》', isHot: false },
  { name: '持经观音', sanskritName: 'Avalokiteśvara-Sutra', otherNames: ['读经观音'], category: '菩萨', summary: '手持经典的观音。', story: '持经观音手持经卷，象征般若智慧。', scripture: '《观音感应传》', isHot: false },
  { name: '岩户观音', sanskritName: 'Avalokiteśvara-Cave', otherNames: ['岩石观音'], category: '菩萨', summary: '在岩窟中显现的观音。', story: '岩户观音端坐于岩窟之中，修习禅定。', scripture: '《观音感应传》', isHot: false },
  { name: '众宝观音', sanskritName: 'Avalokiteśvara-Treasure', otherNames: ['多宝观音'], category: '菩萨', summary: '以众宝装饰的观音。', story: '众宝观音以众宝庄严全身。', scripture: '《观音感应传》', isHot: false },
  { name: '滴水观音', sanskritName: 'Avalokiteśvara-Water', otherNames: ['滴水'], category: '菩萨', summary: '洒滴净水的观音。', story: '滴水观音以宝瓶滴下净水洗净众生。', scripture: '《观音感应传》', isHot: false },
  { name: '游戏观音', sanskritName: 'Avalokiteśvara-Vikrīdita', otherNames: ['游戏坐观音'], category: '菩萨', summary: '以游戏坐姿显现的观音。', story: '游戏观音以游戏坐姿安坐，自在度化众生。', scripture: '《法华经》', isHot: false },
  { name: '青颈观音', sanskritName: 'Avalokiteśvara-Neck-Blue', otherNames: ['青颈'], category: '菩萨', summary: '颈部呈青色的观音。', story: '青颈观音能破一切灾祸。', scripture: '《观音感应传》', isHot: false },
  { name: '合掌观音', sanskritName: 'Avalokiteśvara-Palms-Joined', otherNames: ['合掌'], category: '菩萨', summary: '合掌显现的观音。', story: '合掌观音双手合掌，象征恭敬皈依。', scripture: '《观音感应传》', isHot: false },
  { name: '一叶观音', sanskritName: 'Avalokiteśvara-One-Leaf', otherNames: ['一叶'], category: '菩萨', summary: '乘一叶莲华的观音。', story: '一叶观音乘一叶莲华浮于水面。', scripture: '《观音感应传》', isHot: false },
  { name: '六时观音', sanskritName: 'Avalokiteśvara-Six-Periods', otherNames: ['六时'], category: '菩萨', summary: '昼夜六时护佑众生的观音。', story: '六时观音于昼夜六时勤加守护众生。', scripture: '《观音感应传》', isHot: false },
  { name: '延命观音', sanskritName: 'Avalokiteśvara-Life', otherNames: ['延命'], category: '菩萨', summary: '延命救苦的观音。', story: '延命观音能护持众生延命增福。', scripture: '《观音感应传》', isHot: false },
  { name: '众寂观音', sanskritName: 'Avalokiteśvara-Stillness', otherNames: ['众寂'], category: '菩萨', summary: '以寂静显现的观音。', story: '众寂观音体现一切法寂静。', scripture: '《观音感应传》', isHot: false },
  { name: '能静观音', sanskritName: 'Avalokiteśvara-Quiet', otherNames: ['能静'], category: '菩萨', summary: '以寂静相显现的观音。', story: '能静观音令众生内心平静。', scripture: '《观音感应传》', isHot: false },
  { name: '阿摩提观音', sanskritName: 'Avalokiteśvara-Avatan', otherNames: ['阿摩提'], category: '菩萨', summary: '观音的愤怒化身。', story: '阿摩提观音降伏魔障。', scripture: '《观音感应传》', isHot: false },
  { name: '马郎妇观音', sanskritName: 'Avalokiteśvara-Horse-Merchant', otherNames: ['马郎妇'], category: '菩萨', summary: '化现美女的观音。', story: '马郎妇观音以善巧方便度化众生。', scripture: '《观音感应传》', isHot: false },
  { name: '一如观音', sanskritName: 'Avalokiteśvara-Unity', otherNames: ['一如'], category: '菩萨', summary: '显现真如自性的观音。', story: '一如观音体现诸法平等一如。', scripture: '《观音感应传》', isHot: false },
  { name: '洒水观音', sanskritName: 'Avalokiteśvara-Sprinkling', otherNames: ['洒水'], category: '菩萨', summary: '洒水清净的观音。', story: '洒水观音以清净之水洗净众生罪业。', scripture: '《观音感应传》', isHot: false },
  { name: '叶衣观音', sanskritName: 'Avalokiteśvara-Leaf-Clothed', otherNames: ['叶衣'], category: '菩萨', summary: '以树叶为衣的观音。', story: '叶衣观音以树叶为衣衫。', scripture: '《观音感应传》', isHot: false },
  { name: '琉璃观音', sanskritName: 'Avalokiteśvara-Lapis', otherNames: ['琉璃'], category: '菩萨', summary: '手持琉璃宝珠的观音。', story: '琉璃观音能满足众生一切愿望。', scripture: '《观音感应传》', isHot: false },

  // 度母
  { name: '绿度母', sanskritName: 'Śyāma-tārā', otherNames: ['救度母', '绿度母'], category: '菩萨', summary: '二十一度母之首。', story: '绿度母能救度一切苦难，是藏传佛教最普遍的本尊之一。', scripture: '《绿度母经》', isHot: true },
  { name: '白度母', sanskritName: 'Sita-tārā', otherNames: ['七眼白度母'], category: '菩萨', summary: '具有七眼的度母。', story: '白度母又称七眼白度母，能消除一切恐惧。', scripture: '《大白伞盖经》', isHot: false },
  { name: '红度母', sanskritName: 'Kurukullā', otherNames: ['作明佛母', '咕噜咕咧佛母'], category: '菩萨', summary: '摄受众生的度母。', story: '红度母能摄受一切众生，增添智慧与慈悲。', scripture: '《作明佛母经》', isHot: false },
  { name: '黄度母', sanskritName: 'Jambhala-tārā', otherNames: ['财源度母'], category: '菩萨', summary: '赐予财富的度母。', story: '黄度母能赐予众生财富与福报。', scripture: '《财源度母经》', isHot: false },
  { name: '蓝度母', sanskritName: 'Uṣṇīṣa-vijayā', otherNames: ['顶髻尊胜佛母'], category: '菩萨', summary: '尊胜佛母化身的度母。', story: '蓝度母能除一切魔障。', scripture: '《尊胜佛母经》', isHot: false },

  // 更多菩萨
  { name: '月光童子', sanskritName: 'Candraprabha', otherNames: ['月光菩萨'], category: '菩萨', summary: '月光菩萨的化身。', story: '月光童子象征清凉的慈悲之光。', scripture: '《月光童子经》', isHot: false },
  { name: '日光童子', sanskritName: 'Sūryaprabha', otherNames: ['日光菩萨'], category: '菩萨', summary: '日光菩萨的化身。', story: '日光童子象征智慧的太阳之光。', scripture: '《日光童子经》', isHot: false },
  { name: '贤护菩萨', sanskritName: 'Bhadrapāla', otherNames: ['贤护', '善守'], category: '菩萨', summary: '在家菩萨的代表。', story: '贤护菩萨是著名的在家菩萨，护持正法。', scripture: '《贤护经》', isHot: false },
  { name: '网明菩萨', sanskritName: 'Jālinīprabha', otherNames: ['网明'], category: '菩萨', summary: '以智慧光照耀众生。', story: '网明菩萨的智慧光明如同宝网。', scripture: '《华严经》', isHot: false },
  { name: '普眼菩萨', sanskritName: 'Samanta-mukha', otherNames: ['普眼'], category: '菩萨', summary: '普遍观察之眼。', story: '普眼菩萨具有普遍观察一切法的智慧之眼。', scripture: '《华严经》', isHot: false },
  { name: '金刚幢菩萨', sanskritName: 'Vajra-dhvaja', otherNames: ['金刚幢'], category: '菩萨', summary: '象征坚固不退。', story: '金刚幢菩萨象征坚固的誓愿。', scripture: '《华严经》', isHot: false },
  { name: '天冠菩萨', sanskritName: 'Mukuṭaka', otherNames: ['天冠'], category: '菩萨', summary: '以天冠为饰的菩萨。', story: '天冠菩萨以宝冠庄严。', scripture: '《华严经》', isHot: false },
  { name: '智积菩萨', sanskritName: 'Siddhārtha', otherNames: ['智积'], category: '菩萨', summary: '象征智慧积累。', story: '智积菩萨象征修行智慧不断积累。', scripture: '《华严经》', isHot: false },
  { name: '辨积菩萨', sanskritName: 'Pratibhāna', otherNames: ['辨积'], category: '菩萨', summary: '象征辩才无碍。', story: '辨积菩萨以无碍辩才著称。', scripture: '《华严经》', isHot: false },
  { name: '宝髻菩萨', sanskritName: 'Maṇi-śikhara', otherNames: ['宝髻'], category: '菩萨', summary: '以宝髻为饰的菩萨。', story: '宝髻菩萨头顶宝髻，象征尊贵。', scripture: '《华严经》', isHot: false },
  { name: '金网菩萨', sanskritName: 'Kāñcana-jāla', otherNames: ['金网'], category: '菩萨', summary: '如金网护持众生。', story: '金网菩萨以金色宝网救护众生。', scripture: '《华严经》', isHot: false },

  // 佛部更多
  { name: '智友佛', sanskritName: 'Jñānāntarīya', otherNames: ['智友'], category: '佛', summary: '辅助释迦牟尼的佛。', story: '智友佛是辅助释迦牟尼佛教化的佛。', scripture: '《大宝积经》', isHot: false },
  { name: '师子佛', sanskritName: 'Simha', otherNames: ['狮子佛'], category: '佛', summary: '以狮子吼说法的佛。', story: '师子佛以狮子吼破除众生邪见。', scripture: '《大宝积经》', isHot: false },
  { name: '觉支佛', sanskritName: 'Buddha-Sambhava', otherNames: ['觉分佛'], category: '佛', summary: '觉悟一切的佛。', story: '觉支佛象征圆满的觉悟。', scripture: '《大宝积经》', isHot: false },
  { name: '华盛佛', sanskritName: 'Pundarīka', otherNames: ['芬陀利佛'], category: '佛', summary: '如白莲华的佛。', story: '华盛佛象征清净如莲。', scripture: '《大宝积经》', isHot: false },
  { name: '山王佛', sanskritName: 'Parvateśvara', otherNames: ['山王'], category: '佛', summary: '如山一般的佛。', story: '山王佛巍峨庄严。', scripture: '《大宝积经》', isHot: false },
  { name: '身义佛', sanskritName: 'Kāya-artha', otherNames: ['身义'], category: '佛', summary: '身体与意义圆满的佛。', story: '身义佛象征身德圆满。', scripture: '《大宝积经》', isHot: false },
  { name: '衣王佛', sanskritName: 'Kiṃśuka', otherNames: ['衣王'], category: '佛', summary: '以法衣庄严的佛。', story: '衣王佛以法衣庄严。', scripture: '《大宝积经》', isHot: false },
  { name: '臂佛', sanskritName: 'Bāhu-ārya', otherNames: ['圣臂佛'], category: '佛', summary: '以圣臂救度众生的佛。', story: '臂佛以大慈悲救度众生。', scripture: '《大宝积经》', isHot: false },
  { name: '月藏佛', sanskritName: 'Candra-garbha', otherNames: ['月藏'], category: '佛', summary: '如月亮的佛。', story: '月藏佛象征清凉慈悲。', scripture: '《大宝积经》', isHot: false },
  { name: '日藏佛', sanskritName: 'Sūrya-garbha', otherNames: ['日藏'], category: '佛', summary: '如太阳的佛。', story: '日藏佛象征智慧光明。', scripture: '《大宝积经》', isHot: false },
  { name: '善戒佛', sanskritName: 'Sīla-dhara', otherNames: ['善戒'], category: '佛', summary: '善持戒律的佛。', story: '善戒佛以清净戒律著称。', scripture: '《大宝积经》', isHot: false },
  { name: '妙意佛', sanskritName: 'Sūcī-kāra', otherNames: ['妙意'], category: '佛', summary: '具有微妙智慧的佛。', story: '妙意佛以微妙智慧度化众生。', scripture: '《大宝积经》', isHot: false },
  { name: '花德佛', sanskritName: 'Puṣpa-dharma', otherNames: ['花法佛'], category: '佛', summary: '以法华为庄严的佛。', story: '花德佛以法华庄严。', scripture: '《大宝积经》', isHot: false },
  { name: '音声佛', sanskritName: 'Sarvākāra', otherNames: ['音声'], category: '佛', summary: '以音声说法的佛。', story: '音声佛以微妙音声转法轮。', scripture: '《大宝积经》', isHot: false },
  { name: '威势佛', sanskritName: 'Mahā-tejas', otherNames: ['威势'], category: '佛', summary: '具有大威德的佛。', story: '威势佛具有大威神力。', scripture: '《大宝积经》', isHot: false },
  { name: '那罗延佛', sanskritName: 'Nārāyaṇa', otherNames: ['那罗延'], category: '佛', summary: '如那罗延天的佛。', story: '那罗延佛具有大力。', scripture: '《大宝积经》', isHot: false },
  { name: '金刚佛', sanskritName: 'Vajra-naya', otherNames: ['金刚'], category: '佛', summary: '如金刚坚固的佛。', story: '金刚佛坚不可摧。', scripture: '《大宝积经》', isHot: false },
  { name: '转轮圣王', sanskritName: 'Cakra-vartin', otherNames: ['转轮王', '转轮圣王'], category: '其他', summary: '统治世界的圣王。', story: '转轮圣王有金轮、银轮、铜轮、铁轮四种，统治四大部洲。', scripture: '《长阿含经》', isHot: false },
  { name: '顶生王', sanskritName: 'Māndhātā', otherNames: ['顶生', '曼陀王'], category: '其他', summary: '古代转轮圣王。', story: '顶生王是过去著名的转轮圣王，曾统治四大部洲。', scripture: '《长阿含经》', isHot: false },
  { name: '灯王佛', sanskritName: 'Dīpaṃkara', otherNames: ['燃灯佛'], category: '佛', summary: '如灯照明黑暗。', story: '灯王佛以智慧之灯照破无明黑暗。', scripture: '《大宝积经》', isHot: false },

  // 更多罗汉
  { name: '施饿鬼罗汉', sanskritName: 'Kāla', otherNames: ['施饿鬼'], category: '罗汉', summary: '专门救度饿鬼的罗汉。', story: '施饿鬼罗汉以法力救度饿鬼道众生。', scripture: '《焰口经》', isHot: false },
  { name: '降龙罗汉', sanskritName: 'Nāga-ji', otherNames: ['降龙'], category: '罗汉', summary: '能降伏龙族的罗汉。', story: '降龙罗汉有降伏毒龙的能力。', scripture: '《法住记》', isHot: false },
  { name: '伏虎罗汉', sanskritName: 'Vyāghra-ji', otherNames: ['伏虎'], category: '罗汉', summary: '能降伏虎妖的罗汉。', story: '伏虎罗汉有降伏虎妖的能力。', scripture: '《法住记》', isHot: false },
  { name: '捧经罗汉', sanskritName: 'Sūtra-dhara', otherNames: ['捧经'], category: '罗汉', summary: '手捧经卷的罗汉。', story: '捧经罗汉恭敬佛法。', scripture: '《法住记》', isHot: false },
  { name: '戏象罗汉', sanskritName: 'Hasti-ājānīya', otherNames: ['戏象'], category: '罗汉', summary: '与象嬉戏的罗汉。', story: '戏象罗汉具有调伏大象的功德。', scripture: '《法住记》', isHot: false },
  { name: '戏狮罗汉', sanskritName: 'Simha-sāhvaya', otherNames: ['戏狮'], category: '罗汉', summary: '与狮同住的罗汉。', story: '戏狮罗汉具有调伏狮子的功德。', scripture: '《法住记》', isHot: false },
  { name: '芭蕉罗汉', sanskritName: 'Taṭākī', otherNames: ['芭蕉'], category: '罗汉', summary: '在芭蕉林修行的罗汉。', story: '芭蕉罗汉在芭蕉林中专修禅定。', scripture: '《法住记》', isHot: false },
  { name: '木瓜罗汉', sanskritName: 'Bimbajātī', otherNames: ['木瓜'], category: '罗汉', summary: '以木瓜为名的罗汉。', story: '木瓜罗汉名字来源于其前世的善行。', scripture: '《法住记》', isHot: false },
  { name: '散花罗汉', sanskritName: 'Puṣpa-dāna', otherNames: ['散花'], category: '罗汉', summary: '散花供养的罗汉。', story: '散花罗汉常散花供养三宝。', scripture: '《法住记》', isHot: false },
  { name: '读经罗汉', sanskritName: 'Sūtra-likhana', otherNames: ['读经'], category: '罗汉', summary: '读诵经典的罗汉。', story: '读经罗汉常读诵经典。', scripture: '《法住记》', isHot: false },

  // 更多护法
  { name: '宝藏神', sanskritName: 'Jambhala', otherNames: ['黄财神', '宝藏神'], category: '护法', summary: '掌管宝藏与财富的护法神。', story: '宝藏神能赐予众生财富和福报。', scripture: '《宝藏神经》', isHot: false },
  { name: '财源天女', sanskritName: 'Vasudhārā', otherNames: ['持世天女', '财源天女'], category: '护法', summary: '赐予财富的女护法。', story: '财源天女能赐予众生无尽的财富。', scripture: '《财源天女经》', isHot: false },
  { name: '地天', sanskritName: 'Pṛthivī', otherNames: ['坚牢地神', '大地女神'], category: '护法', summary: '主管大地的女神。', story: '地天护持一切草木药物生长。', scripture: '《金光明经》', isHot: false },
  { name: '火天', sanskritName: 'Agni', otherNames: ['火神', '火头金刚'], category: '护法', summary: '主管火焰的神。', story: '火天能焚烧一切众生的烦恼障碍。', scripture: '《大日经》', isHot: false },
  { name: '水天', sanskritName: 'Varuṇa', otherNames: ['水神', '婆罗那'], category: '护法', summary: '主管水域的神。', story: '水天护持一切水族众生。', scripture: '《大日经》', isHot: false },
  { name: '风天', sanskritName: 'Vāyu', otherNames: ['风神'], category: '护法', summary: '主管风的神。', story: '风天护持一切有情。', scripture: '《大日经》', isHot: false },
  { name: '伊舍那天', sanskritName: 'İśāna', otherNames: ['大自在天', '自在天'], category: '护法', summary: '主管一切的神。', story: '伊舍那天是印度教湿婆神在佛教中的化现。', scripture: '《大日经》', isHot: false },
  { name: '梵天', sanskritName: 'Brahmā', otherNames: ['大梵天王'], category: '护法', summary: '主管梵天的神。', story: '梵天请佛说法，护持正法。', scripture: '《华严经》', isHot: false },
  { name: '帝释天', sanskritName: 'Śakra', otherNames: ['释提桓因', '天帝'], category: '护法', summary: '忉利天之主。', story: '帝释天多次请佛说法，护持正法。', scripture: '《阿含经》', isHot: false },
  { name: '遍入天', sanskritName: 'Viṣṇu', otherNames: ['毗湿奴', '遍净天'], category: '护法', summary: '印度教神祇被佛教吸收为护法。', story: '遍入天被佛教吸收为护法神。', scripture: '《大日经》', isHot: false },
  { name: '太阳天子', sanskritName: 'Sūrya', otherNames: ['日天', '日光天子'], category: '护法', summary: '主管太阳的神。', story: '太阳天子以光明照破黑暗。', scripture: '《大日经》', isHot: false },
  { name: '月亮天子', sanskritName: 'Candra', otherNames: ['月天', '月光天子'], category: '护法', summary: '主管月亮的神。', story: '月亮天子以清凉照破热恼。', scripture: '《大日经》', isHot: false },
  { name: '星宿天子', sanskritName: 'Nakṣatra', otherNames: ['星宿天'], category: '护法', summary: '主管星辰的神。', story: '星宿天子护持一切修行者。', scripture: '《大日经》', isHot: false },
  { name: '阎魔罗王', sanskritName: 'Yama-rāja', otherNames: ['阎罗王', '阎王'], category: '护法', summary: '地狱之主。', story: '阎魔罗王审判众生善恶。', scripture: '《长阿含经》', isHot: false },
  { name: '泰山府君', sanskritName: 'Taishan', otherNames: ['东岳大帝'], category: '护法', summary: '中国道教神被佛教吸收为护法。', story: '泰山府君主管人的生死祸福。', scripture: '', isHot: false },
  { name: '面然大士', sanskritName: 'Mahākāla', otherNames: ['面燃大士', '鬼王'], category: '护法', summary: '焰口鬼王。', story: '面然大士是饿鬼道中的大菩萨。', scripture: '《焰口经》', isHot: false },
  { name: '监斋菩萨', sanskritName: 'Kṣitigarbha', otherNames: ['监斋神'], category: '护法', summary: '寺院监斋护法。', story: '监斋菩萨护持寺院饮食。', scripture: '', isHot: false },
  { name: '妙眼护法', sanskritName: 'Sūkṣma-dṛk', otherNames: ['妙眼'], category: '护法', summary: '具有微妙智慧的护法。', story: '妙眼护法能洞察一切。', scripture: '《药师经》', isHot: false },
  { name: '大功德护法', sanskritName: 'Mahā-guṇa', otherNames: ['大功德'], category: '护法', summary: '具有大功德的护法。', story: '大功德护法护持正法。', scripture: '《药师经》', isHot: false },

  // 更多高僧大德
  { name: '道安', sanskritName: 'Daoan', otherNames: ['道安法师'], category: '其他', summary: '东晋高僧，中国佛教奠基人之一。', story: '道安大师统一了沙门姓氏为释氏，整理佛经，确立僧团规范。', scripture: '《鼻奈耶》', isHot: false },
  { name: '法显', sanskritName: 'Faxian', otherNames: ['法显大师'], category: '其他', summary: '西行求法的先驱。', story: '法显是第一位到达印度求法的中国僧人，著有《佛国记》。', scripture: '《佛国记》', isHot: false },
  { name: '义净', sanskritName: 'Yijing', otherNames: ['义净法师'], category: '其他', summary: '唐代高僧，西行求法者。', story: '义净继法显之后西行求法，著有《西域记》。', scripture: '《大唐西域记》', isHot: false },
  { name: '慧远', sanskritName: 'Huiyuan', otherNames: ['慧远大师', '莲宗初祖'], category: '其他', summary: '净土宗初祖。', story: '慧远于庐山结白莲社，专修念佛三昧。', scripture: '《念佛三昧诗集》', isHot: false },
  { name: '道宣', sanskritName: 'Daoxuan', otherNames: ['道宣律师'], category: '其他', summary: '南山律宗创始人。', story: '道宣创立南山律宗，整理佛教戒律。', scripture: '《四分律删补比丘尼戒本》', isHot: false },
  { name: '道绰', sanskritName: 'Daochuo', otherNames: ['道绰法师'], category: '其他', summary: '净土宗高僧。', story: '道绰倡导持名念佛，劝人念阿弥陀佛。', scripture: '《安乐集》', isHot: false },
  { name: '善导', sanskritName: 'Shandao', otherNames: ['善导大师'], category: '其他', summary: '净土宗第二代祖师。', story: '善导大师弘扬持名念佛，著作《观无量寿经疏》。', scripture: '《观无量寿经疏》', isHot: false },
  { name: '慧日', sanskritName: 'Huiri', otherNames: ['慧日法师'], category: '其他', summary: '净土宗高僧。', story: '慧日提倡念佛往生西方极乐世界。', scripture: '《净土论》', isHot: false },
  { name: '慧远', sanskritName: 'Huiyuan', otherNames: ['慧远法师'], category: '其他', summary: '天台宗高僧。', story: '慧远法师弘扬天台宗教义。', scripture: '《法华玄义》', isHot: false },
  { name: '智顗', sanskritName: 'Zhiyi', otherNames: ['智者大师', '天台大师'], category: '其他', summary: '天台宗创始人。', story: '智顗创立天台宗，主张定慧双修。', scripture: '《法华玄义》《摩诃止观》', isHot: false },
  { name: '吉藏', sanskritName: 'Jizang', otherNames: ['吉藏法师'], category: '其他', summary: '三论宗创始人。', story: '吉藏创立三论宗，弘扬龙树中观学说。', scripture: '《三论玄义》', isHot: false },
  { name: '法藏', sanskritName: 'Fazang', otherNames: ['法藏大师'], category: '其他', summary: '华严宗高僧。', story: '法藏弘扬华严宗，著作《华严经探玄记》。', scripture: '《华严经探玄记》', isHot: false },
  { name: '澄观', sanskritName: 'Chengguan', otherNames: ['澄观大师'], category: '其他', summary: '华严宗四祖。', story: '澄观弘扬华严宗，著作《华严经疏》。', scripture: '《华严经疏》', isHot: false },
  { name: '慧光', sanskritName: 'Hui Guang', otherNames: ['慧光律师'], category: '其他', summary: '四分律宗创始人。', story: '慧光创立四分律宗，弘扬戒律。', scripture: '《四分律》', isHot: false },
  { name: '慧祐', sanskritName: 'Hui You', otherNames: ['慧祐律师'], category: '其他', summary: '四分律宗高僧。', story: '慧祐继承慧光律师弘扬律宗。', scripture: '《四分律》', isHot: false },
  { name: '慧远', sanskritName: 'Hui Yuan', otherNames: ['慧远法师'], category: '其他', summary: '地藏宗高僧。', story: '慧远专弘地藏法门。', scripture: '《地藏十轮经》', isHot: false },
  { name: '慧果', sanskritName: 'Huiguo', otherNames: ['慧果阿阇梨'], category: '其他', summary: '密宗高僧。', story: '慧果为唐代密宗大师，弘扬真言宗。', scripture: '《大日经疏》', isHot: false },
  { name: '空海', sanskritName: 'Kukai', otherNames: ['弘法大师'], category: '其他', summary: '日本真言宗创始人。', story: '空海入唐求法，回日本创立真言宗。', scripture: '《即身成佛义》', isHot: false },
  { name: '最澄', sanskritName: 'Saicho', otherNames: ['传教大师'], category: '其他', summary: '日本天台宗创始人。', story: '最澄入唐求法，回日本创立天台宗。', scripture: '《法华玄义》', isHot: false },
  { name: '法相', sanskritName: 'Faxiang', otherNames: ['法相宗'], category: '其他', summary: '法相宗高僧。', story: '法相宗以唯识学为核心。', scripture: '《成唯识论》', isHot: false },
  { name: '慧远', sanskritName: 'Hui Yuan', otherNames: ['慧远法师'], category: '其他', summary: '摄论宗高僧。', story: '慧远弘扬摄大乘论。', scripture: '《摄大乘论》', isHot: false },
  { name: '慧光', sanskritName: 'Hui Guang', otherNames: ['慧光法师'], category: '其他', summary: '涅槃宗高僧。', story: '慧光弘扬涅槃经。', scripture: '《涅槃经》', isHot: false },
  { name: '慧可', sanskritName: 'Huike', otherNames: ['慧可大师'], category: '其他', summary: '禅宗二祖。', story: '慧可是禅宗二祖，为达摩祖师的弟子。', scripture: '《血脉论》', isHot: false },
  { name: '僧璨', sanskritName: 'Sengcan', otherNames: ['僧璨大师'], category: '其他', summary: '禅宗三祖。', story: '僧璨是禅宗三祖，著作《信心铭》。', scripture: '《信心铭》', isHot: false },
  { name: '道信', sanskritName: 'Daoxin', otherNames: ['道信大师'], category: '其他', summary: '禅宗四祖。', story: '道信是禅宗四祖，主张安心修行。', scripture: '《入道安心要方便法门》', isHot: false },
  { name: '弘忍', sanskritName: 'Hongren', otherNames: ['弘忍大师'], category: '其他', summary: '禅宗五祖。', story: '弘忍是禅宗五祖，传承东山法门。', scripture: '《最上乘论》', isHot: false },
  { name: '神秀', sanskritName: 'Shenxiu', otherNames: ['神秀大师'], category: '其他', summary: '禅宗北宗创始人。', story: '神秀弘扬渐悟法门，为禅宗北宗之祖。', scripture: '《观心论》', isHot: false },
  { name: '慧能', sanskritName: 'Huinan', otherNames: ['六祖慧能'], category: '其他', summary: '禅宗六祖，南宗创始人。', story: '慧能开创禅宗南宗，提倡顿悟法门。', scripture: '《六祖坛经》', isHot: true },
  { name: '怀海', sanskritName: 'Huaihai', otherNames: ['怀海禅师'], category: '其他', summary: '百丈怀海，禅宗高僧。', story: '百丈怀海制立清规，创立禅院制度。', scripture: '《百丈清规》', isHot: false },
  { name: '希运', sanskritName: 'Xiyun', otherNames: ['希运禅师'], category: '其他', summary: '临济宗高僧。', story: '希运是临济宗之祖，提倡当头棒喝。', scripture: '《黄檗山断际禅师传心法要》', isHot: false },
  { name: '义玄', sanskritName: 'Yixuan', otherNames: ['义玄禅师'], category: '其他', summary: '临济宗创始人。', story: '义玄创立临济宗，以机锋锐利著称。', scripture: '《临济录》', isHot: false },
  { name: '从谂', sanskritName: 'Congshen', otherNames: ['从谂禅师'], category: '其他', summary: '赵州禅师。', story: '从谂住赵州观音院，以赵州茶闻名。', scripture: '《赵州录》', isHot: false },
  { name: '慧寂', sanskritName: 'Huiji', otherNames: ['慧寂禅师'], category: '其他', summary: '沩仰宗创始人之一。', story: '慧寂与灵祐共同创立沩仰宗。', scripture: '《沩山警策》', isHot: false },
  { name: '灵祐', sanskritName: 'Lingyou', otherNames: ['灵祐禅师'], category: '其他', summary: '沩仰宗创始人之一。', story: '灵祐住沩山，创立沩仰宗。', scripture: '《沩山警策》', isHot: false },
  { name: '良价', sanskritName: 'Liangjie', otherNames: ['良价禅师'], category: '其他', summary: '曹洞宗创始人之一。', story: '良价创立曹洞宗，以默照禅著称。', scripture: '《曹山录》', isHot: false },
  { name: '本寂', sanskritName: 'Benji', otherNames: ['本寂禅师'], category: '其他', summary: '曹洞宗创始人之一。', story: '本寂与良价共同创立曹洞宗。', scripture: '《抚州曹山本寂禅师录》', isHot: false },
  { name: '文偃', sanskritName: 'Wenyan', otherNames: ['文偃禅师'], category: '其他', summary: '云门宗创始人。', story: '文偃创立云门宗，以云门三句著称。', scripture: '《云门录》', isHot: false },
  { name: '法眼', sanskritName: 'Fayan', otherNames: ['法眼禅师'], category: '其他', summary: '法眼宗创始人。', story: '法眼创立法眼宗，提倡禅教合一。', scripture: '《法眼录》', isHot: false },
  { name: '永明延寿', sanskritName: 'Yongming Yanshou', otherNames: ['永明大师'], category: '其他', summary: '五代宋初高僧，净土宗六祖。', story: '永明延寿提倡禅净双修，著作《宗镜录》。', scripture: '《宗镜录》《万善同归集》', isHot: false },
  { name: '莲池祩', sanskritName: 'Lianchi Zhu', otherNames: ['莲池祩大师'], category: '其他', summary: '明代四大高僧之一，净土宗八祖。', story: '莲池祩提倡念佛往生，著作《阿弥陀经疏钞》。', scripture: '《阿弥陀经疏钞》', isHot: false },
  { name: '蕅益智旭', sanskritName: 'Ouyi Zhixu', otherNames: ['蕅益大师'], category: '其他', summary: '明代四大高僧之一。', story: '蕅益提倡禅教律净合一，著作《灵峰宗论》。', scripture: '《灵峰宗论》', isHot: false },
  { name: '紫柏真可', sanskritName: 'Zibai Zhenke', otherNames: ['紫柏大师'], category: '其他', summary: '明代四大高僧之一。', story: '紫柏真可提倡佛法改革，著作《紫柏老人集》。', scripture: '《紫柏老人集》', isHot: false },
  { name: '憨山德清', sanskritName: 'Hanshan Deqing', otherNames: ['憨山大师'], category: '其他', summary: '明代四大高僧之一。', story: '憨山德清提倡禅净双修，著作《憨山老人梦游集》。', scripture: '《憨山老人梦游集》', isHot: false },
  { name: '云门湛然', sanskritName: 'Yunmen Zhanran', otherNames: ['湛然大师'], category: '其他', summary: '天台宗高僧。', story: '湛然提倡天台宗中兴，著作《法华玄义释签》。', scripture: '《法华玄义释签》', isHot: false },
  { name: '贤首', sanskritName: 'Xianshou', otherNames: ['贤首法师'], category: '其他', summary: '华严宗三祖。', story: '贤首创立华严宗，著作《华严经还源观》。', scripture: '《华严经还源观》', isHot: false },
  { name: '清凉澄观', sanskritName: 'Qingliang Chengguan', otherNames: ['清凉澄观'], category: '其他', summary: '华严宗四祖。', story: '清凉澄观弘扬华严宗，著作《华严经疏》。', scripture: '《华严经疏》', isHot: false },
  { name: '圭峰宗密', sanskritName: 'Guifeng Zongmi', otherNames: ['宗密大师'], category: '其他', summary: '华严宗五祖。', story: '宗密提倡禅教合一，著作《禅源诸诠集都序》。', scripture: '《禅源诸诠集都序》', isHot: false },
  { name: '马祖道一', sanskritName: 'Mazu Daoyi', otherNames: ['马祖道一'], category: '其他', summary: '唐代禅宗高僧。', story: '马祖道一创立洪州宗，以平常心是道著称。', scripture: '《马祖语录》', isHot: false },
  { name: '黄檗希运', sanskritName: 'Huangbo Xiyun', otherNames: ['黄檗希运'], category: '其他', summary: '唐代禅宗高僧。', story: '黄檗希运提倡直接顿悟，著作《黄檗断际禅师宛陵录》。', scripture: '《黄檗断际禅师宛陵录》', isHot: false },
  { name: '临济义玄', sanskritName: 'Linji Yixuan', otherNames: ['临济义玄'], category: '其他', summary: '临济宗创始人。', story: '临济义玄创立临济宗，以四料简四宾主著称。', scripture: '《临济录》', isHot: false },
  { name: '德山宣鉴', sanskritName: 'Deshan Xuanjian', otherNames: ['德山宣鉴'], category: '其他', summary: '唐代禅宗高僧。', story: '德山宣鉴以呵佛骂祖著称。', scripture: '《德山语录》', isHot: false },
  { name: '雪峰义存', sanskritName: 'Xuefeng Yicun', otherNames: ['雪峰义存'], category: '其他', summary: '唐代禅宗高僧。', story: '雪峰义存创立雪峰宗，弟子遍布天下。', scripture: '《雪峰语录》', isHot: false },
  { name: '玄沙师备', sanskritName: 'Xuansha Shibei', otherNames: ['玄沙师备'], category: '其他', summary: '唐代禅宗高僧。', story: '玄沙师备提倡看话禅。', scripture: '《玄沙语录》', isHot: false },
  { name: '云门文偃', sanskritName: 'Yunmen Wenyan', otherNames: ['云门文偃'], category: '其他', summary: '云门宗创始人。', story: '云门文偃创立云门宗，以云门三句著称。', scripture: '《云门录》', isHot: false },
  { name: '曹山本寂', sanskritName: 'Caoshan Benji', otherNames: ['曹山本寂'], category: '其他', summary: '曹洞宗创始人之一。', story: '曹山本寂与良价共同创立曹洞宗。', scripture: '《曹山录》', isHot: false },
  { name: '洞山良价', sanskritName: 'Dongshan Liangjie', otherNames: ['洞山良价'], category: '其他', summary: '曹洞宗创始人之一。', story: '洞山良价创立曹洞宗，以偏正回互著称。', scripture: '《洞山语录》', isHot: false },
  { name: '夹山善会', sanskritName: 'Jiashan Shanhui', otherNames: ['夹山善会'], category: '其他', summary: '唐代禅宗高僧。', story: '夹山善会提倡三藏教。', scripture: '《夹山语录》', isHot: false },
  { name: '洛浦元安', sanskritName: 'LuoPu YuanAn', otherNames: ['洛浦元安'], category: '其他', summary: '唐代禅宗高僧。', story: '洛浦元安是夹山善会法嗣。', scripture: '《洛浦录》', isHot: false },
  { name: '船子德诚', sanskritName: 'Chuanzi Decheng', otherNames: ['船子德诚'], category: '其他', summary: '唐代禅宗高僧。', story: '船子德诚以垂钓度化众生。', scripture: '《船子逸歌》', isHot: false },
  { name: '投子义渊', sanskritName: 'Touzi Yiyuan', otherNames: ['投子义渊'], category: '其他', summary: '宋代禅宗高僧。', story: '投子义渊是曹洞宗高僧。', scripture: '《投子语录》', isHot: false },
  { name: '芙蓉道楷', sanskritName: 'Furong Daokai', otherNames: ['芙蓉道楷'], category: '其他', summary: '宋代曹洞宗高僧。', story: '芙蓉道楷继承曹洞宗风。', scripture: '《芙蓉语录》', isHot: false },
  { name: '丹霞天然', sanskritName: 'Danxia Tianran', otherNames: ['丹霞天然'], category: '其他', summary: '唐代禅宗高僧。', story: '丹霞天然曾烧木佛取暖。', scripture: '《丹霞语录》', isHot: false },
  { name: '赵州从谂', sanskritName: 'Zhaozhou Congshen', otherNames: ['赵州从谂'], category: '其他', summary: '唐代赵州禅师。', story: '赵州从谂以赵州茶、赵州话度人。', scripture: '《赵州录》', isHot: false },
  { name: '南泉普愿', sanskritName: 'Nanquan Puyuan', otherNames: ['南泉普愿'], category: '其他', summary: '唐代禅宗高僧。', story: '南泉普愿提倡平常心是道。', scripture: '《南泉语录》', isHot: false },
  { name: '百丈怀海', sanskritName: 'Baizhang Huanghai', otherNames: ['百丈怀海'], category: '其他', summary: '唐代禅宗高僧。', story: '百丈怀海创立丛林制度，著作《百丈清规》。', scripture: '《百丈清规》', isHot: false },
  { name: '黄檗断际', sanskritName: 'Huangbo Duanji', otherNames: ['黄檗断际'], category: '其他', summary: '唐代禅宗高僧。', story: '黄檗断际提倡直接顿悟。', scripture: '《黄檗断际禅师传心法要》', isHot: false },
  { name: '临济慧然', sanskritName: 'Linji Huiran', otherNames: ['临济慧然'], category: '其他', summary: '宋代临济宗高僧。', story: '临济慧然继承临济宗风。', scripture: '《临济录》', isHot: false },
  { name: '大慧宗杲', sanskritName: 'Dahui Zonggao', otherNames: ['大慧宗杲'], category: '其他', summary: '宋代临济宗高僧，看话禅创始人。', story: '大慧宗杲提倡看话禅，以参公案著称。', scripture: '《大慧语录》', isHot: false },
  { name: '无门慧开', sanskritName: 'Wumen Huikai', otherNames: ['无门慧开'], category: '其他', summary: '宋代临济宗高僧。', story: '无门慧开著作《无门关》，提倡看话禅。', scripture: '《无门关》', isHot: false },
  { name: '万松行秀', sanskritName: 'Wansong Xingxiu', otherNames: ['万松行秀'], category: '其他', summary: '金代曹洞宗高僧。', story: '万松行秀提倡默照禅。', scripture: '《万松语录》', isHot: false },
  { name: '雪窦重显', sanskritName: 'Xuedou Chongxian', otherNames: ['雪窦重显'], category: '其他', summary: '宋代云门宗高僧。', story: '雪窦重显提倡云门宗风。', scripture: '《雪窦语录》', isHot: false },
  { name: '圆悟克勤', sanskritName: 'Yuanwu Keqin', otherNames: ['圆悟克勤'], category: '其他', summary: '宋代临济宗高僧。', story: '圆悟克勤提倡文字禅，著作《碧岩录》。', scripture: '《碧岩录》', isHot: false },
  { name: '虎丘绍隆', sanskritName: 'Huqiu Shaolong', otherNames: ['虎丘绍隆'], category: '其他', summary: '宋代临济宗高僧。', story: '虎丘绍隆是圆悟克勤法嗣。', scripture: '《虎丘语录》', isHot: false },
  { name: '应庵昙华', sanskritName: 'Ying-an Tanhua', otherNames: ['应庵昙华'], category: '其他', summary: '宋代临济宗高僧。', story: '应庵昙华是虎丘绍隆法嗣。', scripture: '《应庵语录》', isHot: false },
  { name: '密庵咸杰', sanskritName: 'Mi-an Xianjie', otherNames: ['密庵咸杰'], category: '其他', summary: '宋代临济宗高僧。', story: '密庵咸杰是应庵昙华法嗣。', scripture: '《密庵语录》', isHot: false },
  { name: '破庵祖先', sanskritName: 'Po-an Zuxian', otherNames: ['破庵祖先'], category: '其他', summary: '宋代临济宗高僧。', story: '破庵祖先是密庵咸杰法嗣。', scripture: '《破庵语录》', isHot: false },
  { name: '无准师范', sanskritName: 'Wuzhun Shifan', otherNames: ['无准师范'], category: '其他', summary: '宋代临济宗高僧。', story: '无准师范是破庵祖先法嗣。', scripture: '《无准语录》', isHot: false },
  { name: '雪岩祖钦', sanskritName: 'Xueyan Zuqin', otherNames: ['雪岩祖钦'], category: '其他', summary: '宋代临济宗高僧。', story: '雪岩祖钦提倡参话头。', scripture: '《雪岩语录》', isHot: false },
  { name: '高峰原妙', sanskritName: 'Gaofeng Yuanmiao', otherNames: ['高峰原妙'], category: '其他', summary: '宋代临济宗高僧。', story: '高峰原妙提倡话头禅。', scripture: '《高峰语录》', isHot: false },
  { name: '中峰明本', sanskritName: 'Zhongfeng Mingben', otherNames: ['中峰明本'], category: '其他', summary: '元代临济宗高僧。', story: '中峰明本提倡禅净双修。', scripture: '《中峰语录》', isHot: false },
  { name: '万峰时蔚', sanskritName: 'Wanfeng Shiwei', otherNames: ['万峰时蔚'], category: '其他', summary: '明代临济宗高僧。', story: '万峰时蔚提倡看话禅。', scripture: '《万峰语录》', isHot: false },
  { name: '幻有正传', sanskritName: 'Huanyou Zhengzhuan', otherNames: ['幻有正传'], category: '其他', summary: '明代临济宗高僧。', story: '幻有正传提倡禅宗心法。', scripture: '《幻有语录》', isHot: false },
  { name: '密云圆悟', sanskritName: 'Miyun Yuanwu', otherNames: ['密云圆悟'], category: '其他', summary: '明代临济宗高僧。', story: '密云圆悟提倡克勤圆悟禅风。', scripture: '《密云语录》', isHot: false },
  { name: '破山海明', sanskritName: 'Poshan Haiming', otherNames: ['破山海明'], category: '其他', summary: '明代临济宗高僧。', story: '破山海明提倡禅宗心法。', scripture: '《破山语录》', isHot: false },
  { name: '木陈道忞', sanskritName: 'Muchen Daomin', otherNames: ['木陈道忞'], category: '其他', summary: '明代临济宗高僧。', story: '木陈道忞提倡禅宗心法。', scripture: '《木陈语录》', isHot: false },
  { name: '玉林通琇', sanskritName: 'Yulin Tongxiu', otherNames: ['玉林通琇'], category: '其他', summary: '清代临济宗高僧。', story: '玉林通琇为清代著名禅僧。', scripture: '《玉林语录》', isHot: false },
  { name: '行策截流', sanskritName: 'Xingce Jieliu', otherNames: ['行策截流'], category: '其他', summary: '清代净土宗高僧。', story: '行策截流提倡净土念佛法门。', scripture: '《起念佛七规式》', isHot: false },
  { name: '省庵实贤', sanskritName: "Sheng'an Shixian", otherNames: ['省庵实贤'], category: '其他', summary: '清代净土宗高僧。', story: '省庵实贤提倡持名念佛。', scripture: '《省庵语录》', isHot: false },
  { name: '彻悟际醒', sanskritName: 'Chewu Jixing', otherNames: ['彻悟际醒'], category: '其他', summary: '清代净土宗高僧。', story: '彻悟际醒提倡禅净双修。', scripture: '《彻悟语录》', isHot: false },
  { name: '印光印光', sanskritName: 'Yinguang', otherNames: ['印光大师'], category: '其他', summary: '近代净土宗高僧。', story: '印光提倡老实念佛，著作《文钞》。', scripture: '《印光法师文钞》', isHot: true },
  { name: '弘一演音', sanskritName: 'Hongyi', otherNames: ['弘一大师'], category: '其他', summary: '近代南山律宗高僧。', story: '弘一法师出家后精研戒律，弘扬南山律宗。', scripture: '《四分律比丘戒相表记》', isHot: true },
  { name: '虚云德清', sanskritName: 'Xuyun', otherNames: ['虚云老和尚'], category: '其他', summary: '近代禅宗高僧。', story: '虚云老和尚修行百年，弘化四方，为现代禅宗泰斗。', scripture: '《虚云和尚年谱》', isHot: true },
  { name: '来果老和尚', sanskritName: 'Laiguo', otherNames: ['来果禅师'], category: '其他', summary: '近代禅宗高僧。', story: '来果老和尚提倡禅宗心法。', scripture: '《来果语录》', isHot: false },
  { name: '倓虚定西', sanskritName: 'Tánxu', otherNames: ['倓虚大师'], category: '其他', summary: '近代天台宗高僧。', story: '倓虚弘法东北，创办极乐寺。', scripture: '《影尘回忆录》', isHot: false },
  { name: '圆瑛讲觉', sanskritName: 'Yuanying', otherNames: ['圆瑛大师'], category: '其他', summary: '近代高僧。', story: '圆瑛大师提倡禅教律净合一。', scripture: '《圆瑛文钞》', isHot: false },
  { name: '太虚义学', sanskritName: 'Taixu', otherNames: ['太虚大师'], category: '其他', summary: '近代佛教改革家。', story: '太虚大师提倡人间佛教，改革佛教。', scripture: '《太虚大师全书》', isHot: true },
  { name: '杨仁山文会', sanskritName: 'Yang Renshan', otherNames: ['杨仁山居士'], category: '其他', summary: '近代居士佛学大师。', story: '杨仁山居士创办金陵刻经处，弘扬佛学。', scripture: '《杨仁山居士遗著》', isHot: false },
  { name: '欧阳竟无', sanskritName: 'Ouyang Jingwu', otherNames: ['欧阳竟无居士'], category: '其他', summary: '近代居士佛学大师。', story: '欧阳竟无提倡唯识学。', scripture: '《欧阳竟无居士文集》', isHot: false },
  { name: '梁漱溟', sanskritName: 'Liang Shuming', otherNames: ['梁漱溟居士'], category: '其他', summary: '近代居士佛学大师。', story: '梁漱溟研究佛教哲学。', scripture: '《印度哲学概论》', isHot: false },
  { name: '李圆净', sanskritName: 'Li Yuanjing', otherNames: ['李圆净居士'], category: '其他', summary: '近代居士佛学大师。', story: '李圆净弘法利生。', scripture: '《李圆净居士文选》', isHot: false },
]

async function main() {
  console.log('Adding new characters...')
  
  let added = 0
  for (const char of newCharacters) {
    try {
      await prisma.character.upsert({
        where: { name: char.name },
        update: {
          sanskritName: char.sanskritName,
          otherNames: JSON.stringify(char.otherNames || []),
          category: char.category,
          summary: char.summary,
          story: char.story || null,
          scripture: char.scripture || null,
          imageUrl: char.imageUrl || null,
          isHot: char.isHot || false,
        },
        create: {
          name: char.name,
          sanskritName: char.sanskritName,
          otherNames: JSON.stringify(char.otherNames || []),
          category: char.category,
          summary: char.summary,
          story: char.story || null,
          scripture: char.scripture || null,
          imageUrl: char.imageUrl || null,
          isHot: char.isHot || false,
          status: 'approved',
        },
      })
      added++
    } catch (e) {
      console.error(`Error adding ${char.name}:`, e.message)
    }
  }
  
  console.log(`Added ${added} new characters.`)
  
  // Print counts
  const counts = await prisma.character.groupBy({
    by: ['category'],
    _count: { category: true },
  })
  console.log('\nCurrent counts:')
  for (const c of counts) {
    console.log(`  ${c.category}: ${c._count.category}`)
  }
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
