import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const characters = [
  // ==================== 佛 ====================
  {
    name: '释迦牟尼佛',
    sanskritName: 'Śākyamuni',
    otherNames: ['佛陀', '世尊', '释迦文佛', '如来'],
    category: '佛',
    summary: '佛教创始人，为娑婆世界教主。释迦牟尼是历史上真实存在的佛陀，创建了延续数千年的佛教教法。',
    story: '释迦牟尼原名乔达摩·悉达多，是古代迦毗罗卫国的王子。他因目睹生老病死而出家寻求解脱，经过六年苦修后在菩提树下悟道成佛。此后说法四十九年，创立了佛教。释迦牟尼佛象征着究竟圆满的智慧与慈悲，是众生学习的楷模。',
    scripture: '《金刚经》《心经》《法华经》《华严经》等',
    isHot: true,
  },
  {
    name: '阿弥陀佛',
    sanskritName: 'Amitābha',
    otherNames: ['无量寿佛', '无量光佛', '接引佛'],
    category: '佛',
    summary: '西方极乐世界的教主，以慈悲愿力接引众生往生净土。',
    story: '阿弥陀佛在因地修行时发下四十八愿，建立西方极乐净土，接引念佛众生往生。释迦牟尼佛在多部经典中赞叹阿弥陀佛的功德，劝导众生求生西方极乐世界。修行者若一心称念阿弥陀佛名号，临终时阿弥陀佛与其眷属会前来接引。',
    scripture: '《无量寿经》《观无量寿经》《阿弥陀经》',
    isHot: true,
  },
  {
    name: '药师佛',
    sanskritName: 'Bhaiṣajyaguru',
    otherNames: ['药师琉璃光如来', '大医王佛'],
    category: '佛',
    summary: '东方净琉璃世界的教主，掌管现世福报与健康。',
    story: '药师佛在因地行菩萨道时发下十二大愿，要解除众生的病苦和灾难。他以琉璃为国土，净琉璃光普照众生。修持药师法门可以消除病苦、延长寿命、消除灾难。药师佛与日光、月光二胁侍菩萨合称「东方三圣」。',
    scripture: '《药师琉璃光如来本愿功德经》',
    isHot: true,
  },
  {
    name: '燃灯佛',
    sanskritName: 'Dīpaṃkara',
    otherNames: ['锭光佛', '普光佛'],
    category: '佛',
    summary: '过去佛，曾为释迦牟尼佛授记，预言其将来成佛。',
    story: '燃灯佛是过去世之佛，曾在娑婆世界说法。释迦牟尼佛前世修行时，曾以头发铺地供养燃灯佛，燃灯佛为其授记：「汝将来成佛，号释迦牟尼。」燃灯佛象征着智慧的传承与延续。',
    scripture: '《瑞应经》《大智度论》',
    isHot: false,
  },
  {
    name: '弥勒佛',
    sanskritName: 'Maitreya',
    otherNames: ['弥勒菩萨', '未来佛', '当来下生弥勒尊佛'],
    category: '佛',
    summary: '未来佛，现居兜率内院，将在释迦牟尼佛法运结束后下生人间成佛。',
    story: '弥勒菩萨现居欲界第四天兜率内院，那里是释迦牟尼佛为未来成佛而准备的净土。弥勒菩萨将在五十六亿七千万年后下生人间，在龙华树下成佛，度化无量众生。弥勒菩萨象征着未来的希望与光明。',
    scripture: '《弥勒上生经》《弥勒下生经》《弥勒三经》',
    isHot: true,
  },
  {
    name: '毗卢遮那佛',
    sanskritName: 'Vairocana',
    otherNames: ['大日如来', '遍照如来', '光明遍照'],
    category: '佛',
    summary: '法身佛，密宗最高本尊，象征宇宙本体的智慧与慈悲。',
    story: '毗卢遮那佛是法身佛，遍一切处，圆满一切。他以大日如来的名号在密教中被崇拜，象征着绝对的真理和智慧。此佛与金刚萨埵、普贤菩萨同体异名，代表法身的三个面向。毗卢遮那佛在《华严经》中宣说圆满的华严境界。',
    scripture: '《大日经》《华严经》',
    isHot: false,
  },
  {
    name: '卢舍那佛',
    sanskritName: 'Lokadhātu-vairocana',
    otherNames: ['报身佛', '圆满报身佛'],
    category: '佛',
    summary: '报身佛，代表修行圆满所证得的佛身。',
    story: '卢舍那佛是报身佛，为地上菩萨所现，是修持圆满所得的果报之身。卢舍那意为「光明遍照」，与法身毗卢遮那、应身释迦牟尼同体异名，代表佛的不同面向。龙门石窟的卢舍那大佛即为报身佛的造像典范。',
    scripture: '《华严经》《梵网经》',
    isHot: false,
  },
  {
    name: '阿閦佛',
    sanskritName: 'Aksobhya',
    otherNames: ['不动佛', '阿閦鞞佛', '不动如来'],
    category: '佛',
    summary: '东方妙喜世界的教主，代表嗔恚不能动摇的定慧。',
    story: '阿閦佛在因地修行时，因修持「嗔怒不起」的法门而证得佛果，建立东方妙喜世界。这位佛象征着通过内心的平静与不动来克服嗔怒和烦恼。其眷属包括金刚萨埵等大菩萨。',
    scripture: '《阿閦佛国经》《大宝积经》',
    isHot: false,
  },
  {
    name: '宝生佛',
    sanskritName: 'Ratnasambhava',
    otherNames: ['宝生如来'],
    category: '佛',
    summary: '南方欢喜世界的教主，象征佛陀的福德与智慧。',
    story: '宝生佛住于南方欢喜世界，象征佛陀圆满的布施、持戒、忍辱、精进、禅定、智慧等六度万行。此佛放金色光，利益一切众生，令众生福智增长。宝生佛是五方佛之一，代表南方。',
    scripture: '《大宝积经》《守护经》',
    isHot: false,
  },
  {
    name: '不空成就佛',
    sanskritName: 'Amoghasiddhi',
    otherNames: ['不空成就如来'],
    category: '佛',
    summary: '北方圆满世界的教主，象征佛陀事业成就圆满。',
    story: '不空成就佛位于北方圆满世界，象征佛法的事业可以无碍成就。此佛能够令一切众生所求满愿，破除一切障碍。不空成就佛是五方佛之一，代表北方方位。',
    scripture: '《大宝积经》',
    isHot: false,
  },
  {
    name: '拘留孙佛',
    sanskritName: 'Krakucchanda',
    otherNames: ['拘留秦佛', '鸠楼孙佛'],
    category: '佛',
    summary: '过去七佛之第四佛，贤劫千佛之首。',
    story: '拘留孙佛是贤劫第一减劫时期出现的佛陀，为人寿四万岁时成佛。当时有一处园林名为「安和」，佛于此地说法度众。拘留孙佛是释迦牟尼佛之前的一位佛陀。',
    scripture: '《长阿含经》《增一阿含经》',
    isHot: false,
  },
  {
    name: '拘那含牟尼佛',
    sanskritName: 'Kanakamuni',
    otherNames: ['迦那迦牟尼佛'],
    category: '佛',
    summary: '过去七佛之第五佛，贤劫第二佛。',
    story: '拘那含牟尼佛于人寿三万岁时在清净国成佛，佛陀觉悟后广说法要，度化无量众生。拘那含牟尼佛象征着清净与智慧。',
    scripture: '《长阿含经》',
    isHot: false,
  },
  {
    name: '迦叶佛',
    sanskritName: 'Kassapa',
    otherNames: ['迦叶波佛'],
    category: '佛',
    summary: '过去七佛之第六佛，贤劫第三佛。',
    story: '迦叶佛于人寿二万岁时成佛，其身色金黄具足三十二相。释迦牟尼佛前世曾供养迦叶佛并受其教化。迦叶佛与释迦牟尼佛有特殊因缘，释迦牟尼佛的弟子中有很多是迦叶佛的弟子转世。',
    scripture: '《长阿含经》',
    isHot: false,
  },
  {
    name: '多宝佛',
    sanskritName: 'Prabhūtaratna',
    otherNames: ['多宝如来'],
    category: '佛',
    summary: '东方宝净世界的佛陀，象征法宝的尊贵。',
    story: '多宝佛在因地修行时发誓：「成佛时，于十方国土中说此法门者，我之塔庙，为听是经故，涌现其前，为作证明。」因此在《法华经》中，释迦牟尼佛讲经时，多宝佛塔从地涌出，为《法华经》作证。',
    scripture: '《妙法莲华经》',
    isHot: false,
  },
  {
    name: '威音王佛',
    sanskritName: 'Sāhasrabhūjā-vajrapāṇi',
    otherNames: ['威音王如来'],
    category: '佛',
    summary: '过去无量微尘劫之佛，象征佛力的广大。',
    story: '威音王佛在很久远劫之前成佛，其佛国名为「胜威」。此佛最初坐道场时，傲慢的捶打声遍十方佛土，大地震动，表明其威德广大。',
    scripture: '《妙法莲华经》',
    isHot: false,
  },

  // ==================== 菩萨 ====================
  {
    name: '观世音菩萨',
    sanskritName: 'Avalokiteśvara',
    otherNames: ['观音菩萨', '观世音', '观音', '南海观音', '送子观音'],
    category: '菩萨',
    summary: '大慈大悲的菩萨，以救苦救难闻名，以慈悲救济众生为本愿。',
    story: '观世音菩萨是阿弥陀佛的左胁侍菩萨，与阿弥陀佛、大势至菩萨合称「西方三圣」。据《法华经》记载，菩萨有三十三应化身，随类度化众生。观世音菩萨的信仰在中国极为普遍，「家家阿弥陀，户户观世音」说明其深入人心。',
    scripture: '《妙法莲华经·观世音菩萨普门品》《心经》《大悲咒》',
    isHot: true,
  },
  {
    name: '文殊菩萨',
    sanskritName: 'Mañjuśrī',
    otherNames: ['文殊师利', '曼珠室利', '妙德', '妙吉祥'],
    category: '菩萨',
    summary: '智慧化身，司一切如来的智慧，与普贤菩萨为华严三圣之一。',
    story: '文殊菩萨代表大智慧，是般若智慧的化身。其形象手持宝剑，骑乘狮子，象征智慧的锐利与威猛。文殊菩萨曾为释迦牟尼佛的左胁侍，在大乘佛教中地位极高。五台山是其道场。',
    scripture: '《文殊师利所说般若波罗蜜经》《华严经》《文殊菩萨发愿经》',
    isHot: true,
  },
  {
    name: '普贤菩萨',
    sanskritName: 'Samantabhadra',
    otherNames: ['普贤如来', '遍吉'],
    category: '菩萨',
    summary: '行愿的象征，代表诸佛的行动愿力，与文殊菩萨为华严三圣之一。',
    story: '普贤菩萨象征理德、定德，与文殊菩萨的智德相对。普贤菩萨的十大愿王闻名于世：「礼敬诸佛、称赞如来、广修供养、忏悔业障、随喜功德、请转法轮、请佛住世、常随佛学、恒顺众生、普皆回向」。峨眉山是其道场。',
    scripture: '《华严经·普贤行愿品》《观普贤菩萨行法经》',
    isHot: true,
  },
  {
    name: '地藏菩萨',
    sanskritName: 'Kṣitigarbha',
    otherNames: ['地藏王菩萨', '地藏'],
    category: '菩萨',
    summary: '誓愿深重的菩萨，发下「地狱不空，誓不成佛」的大愿，救度地狱众生。',
    story: '地藏菩萨在过去世曾为婆罗门女和光目女，为救度亡母而发下大愿。他受释迦牟尼佛嘱托，在释迦牟尼佛灭度后、弥勒佛降生前，担当救度众生的重任。地藏菩萨因其誓愿被称为「大愿地藏」。九华山是其道场。',
    scripture: '《地藏菩萨本愿经》《占察善恶业报经》',
    isHot: true,
  },
  {
    name: '大势至菩萨',
    sanskritName: 'Mahāsthāmaprāpta',
    otherNames: ['得大势菩萨', '大势至'],
    category: '菩萨',
    summary: '阿弥陀佛的右胁侍，以智慧光明普照一切，令众生解脱。',
    story: '大势至菩萨与观世音菩萨同为阿弥陀佛的胁侍，合称「西方三圣」。据《观无量寿经》载，菩萨以智慧光普照一切，令众生离苦得乐。其国土名「安养」，接引众生往生西方极乐世界。',
    scripture: '《观无量寿经》《大方广菩萨藏经》',
    isHot: false,
  },
  {
    name: '弥勒菩萨',
    sanskritName: 'Maitreya',
    otherNames: ['弥勒佛', '阿逸多菩萨'],
    category: '菩萨',
    summary: '未来佛，现为菩萨身份，居兜率天内院，为释迦牟尼佛预言的继任者。',
    story: '弥勒菩萨现在兜率天内院说法，五十六亿七千万年后将下生人间，在龙华树下成佛。弥勒菩萨的信仰源于《弥勒上生经》和《弥勒下生经》。修行弥勒法门可以往生兜率天。',
    scripture: '《弥勒上生经》《弥勒下生经》《弥勒三经》',
    isHot: true,
  },
  {
    name: '金刚手菩萨',
    sanskritName: 'Vajrapāṇi',
    otherNames: ['金刚萨埵', '执金刚菩萨', '金刚手'],
    category: '菩萨',
    summary: '密教重要本尊，象征佛陀的坚固力量与智慧。',
    story: '金刚手菩萨是密教金刚界的本尊，代表佛陀的坚固不坏之力。他手持金刚杵，能破除一切烦恼魔军。金刚手菩萨与普贤菩萨同体异名，在密教中地位极高。',
    scripture: '《金刚顶瑜伽经》《大日经》',
    isHot: false,
  },
  {
    name: '虚空藏菩萨',
    sanskritName: 'Ākāśagarbha',
    otherNames: ['虚空孕菩萨'],
    category: '菩萨',
    summary: '象征智慧的宝藏如虚空般无限，慈悲济度一切众生。',
    story: '虚空藏菩萨以虚空为库藏，蕴育无穷智慧与慈悲。修行此菩萨法门可获辩才无碍、福德圆满。虚空藏菩萨与金刚手菩萨并称，为密教重要本尊。',
    scripture: '《虚空藏菩萨经》《大集经》',
    isHot: false,
  },
  {
    name: '准提菩萨',
    sanskritName: 'Cundī',
    otherNames: ['准提佛母', '七俱胝佛母'],
    category: '菩萨',
    summary: '感应强力的菩萨，密教重要本尊，具有多种功德。',
    story: '准提菩萨是密教莲华部（六道金刚）的本尊，其法门感应迅速。修持准提法可以息灾、增益、敬爱、降伏。准提菩萨形象多为三眼十八臂，代表种种方便救度。',
    scripture: '《准提陀罗尼经》《大乘本生文殊师利观想了一切佛心论》',
    isHot: true,
  },
  {
    name: '除盖障菩萨',
    sanskritName: 'Nivaraṇaviṣkambhin',
    otherNames: ['除一切盖障菩萨'],
    category: '菩萨',
    summary: '消除一切修行障碍的菩萨，象征清净智慧。',
    story: '除盖障菩萨能消除众生修行路上的种种障碍，包括贪欲、嗔恚、愚痴、睡眠、掉举、疑惑、傲慢等障。其法门帮助修行者清净道业。',
    scripture: '《离垢慧菩萨所问经》',
    isHot: false,
  },
  {
    name: '日光菩萨',
    sanskritName: 'Sūryaprabha',
    otherNames: ['日光遍照菩萨'],
    category: '菩萨',
    summary: '药师佛的左胁侍，象征智慧之光普照世间。',
    story: '日光菩萨与月光菩萨同为药师佛的胁侍，合称「东方三圣」。日光菩萨以大悲誓愿普照五道众生，消除业障，令众生智慧增长。',
    scripture: '《药师琉璃光如来本愿功德经》',
    isHot: false,
  },
  {
    name: '月光菩萨',
    sanskritName: 'Candraprabha',
    otherNames: ['月光遍照菩萨'],
    category: '菩萨',
    summary: '药师佛的右胁侍，象征柔和清凉的慈悲之光。',
    story: '月光菩萨与日光菩萨同为药师佛的胁侍，能除一切众生热恼，令得清凉智慧。月光菩萨象征着慈悲与智慧的清凉和解脱。',
    scripture: '《药师琉璃光如来本愿功德经》',
    isHot: false,
  },
  {
    name: '药王菩萨',
    sanskritName: 'Bhaiṣajyaguru-rāja',
    otherNames: ['药王'],
    category: '菩萨',
    summary: '施与众生良药，疗治一切身心病苦的菩萨。',
    story: '药王菩萨在过去世为一切众生喜见菩萨，发愿以医术救治众生。其施药、施身、施命的精神体现了菩萨的大慈大悲。焚身供佛的典故即出自药王菩萨。',
    scripture: '《观药王药上二菩萨经》',
    isHot: false,
  },
  {
    name: '药上菩萨',
    sanskritName: 'Bhaiṣajyaguru-vaidūrya-prabha-rāja',
    otherNames: ['药上'],
    category: '菩萨',
    summary: '药王菩萨之兄，与药王菩萨共同施药救众生。',
    story: '药上菩萨与药王菩萨同为兄弟，发愿救治众生一切病苦。二菩萨共同承担救济众生的使命，象征着医疗与治愈的力量。',
    scripture: '《观药王药上二菩萨经》',
    isHot: false,
  },
  {
    name: '无尽意菩萨',
    sanskritName: 'Aksobhya-tathāgata',
    otherNames: ['无尽慧菩萨'],
    category: '菩萨',
    summary: '象征愿力无穷无尽的菩萨，以无尽誓愿救度众生。',
    story: '无尽意菩萨发下无穷誓愿，要度尽一切众生。其名号象征着菩萨的愿力不可思议。无尽意菩萨在《华严经》中有重要地位。',
    scripture: '《大方广佛华严经》《普贤行愿品》',
    isHot: false,
  },
  {
    name: '宝檀华菩萨',
    sanskritName: 'Gandhāri',
    otherNames: ['宝檀华'],
    category: '菩萨',
    summary: '象征殊妙功德的菩萨。',
    story: '宝檀华菩萨以殊妙的功德之香利益众生，其名号象征着最珍贵的供养和功德。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '思维菩萨',
    sanskritName: 'Maitreyāni',
    otherNames: ['思惟菩萨'],
    category: '菩萨',
    summary: '以智慧思维一切法的菩萨。',
    story: '思维菩萨以甚深智慧观察一切法，思维诸法实相。其修行方式以静虑思维为主。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '大慧菩萨',
    sanskritName: 'Mahābhadra',
    otherNames: ['大慧'],
    category: '菩萨',
    summary: '代表圆满智慧的菩萨。',
    story: '大慧菩萨象征着究竟圆满的智慧，能通达一切佛法。大慧菩萨在很多经典中都有出现。',
    scripture: '《华严经》《楞伽经》',
    isHot: false,
  },
  {
    name: '光明菩萨',
    sanskritName: 'Prabhasvara',
    otherNames: ['光明'],
    category: '菩萨',
    summary: '象征智慧光明的菩萨。',
    story: '光明菩萨以智慧之光照破一切无明黑暗，令众生得见真理。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '金刚幢菩萨',
    sanskritName: 'Vajra-dhvaja',
    otherNames: ['金刚幢'],
    category: '菩萨',
    summary: '象征坚固不退的菩萨。',
    story: '金刚幢菩萨象征着坚固的誓愿，如同金刚宝幢一样不可动摇。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '贤护菩萨',
    sanskritName: 'Bhadrapāla',
    otherNames: ['贤护', '善守'],
    category: '菩萨',
    summary: '在家菩萨的代表，护持正法的菩萨。',
    story: '贤护菩萨是释迦牟尼佛时代著名的在家菩萨，他护持正法、供养三宝，是在家学佛的典范。',
    scripture: '《贤护经》《大集经》',
    isHot: false,
  },
  {
    name: '网明菩萨',
    sanskritName: 'Jālinīprabha',
    otherNames: ['网明'],
    category: '菩萨',
    summary: '以智慧光明照耀众生的菩萨。',
    story: '网明菩萨的智慧光明如同宝网，遍照一切众生，令其开悟。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '天冠菩萨',
    sanskritName: 'Mukuṭaka',
    otherNames: ['天冠'],
    category: '菩萨',
    summary: '以天冠为饰的菩萨。',
    story: '天冠菩萨以其庄严的宝冠闻名，象征着佛法的尊贵与殊胜。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '智积菩萨',
    sanskritName: 'Siddhārtha',
    otherNames: ['智积'],
    category: '菩萨',
    summary: '象征智慧积累的菩萨。',
    story: '智积菩萨象征着修行的智慧不断积累，从量变达到质变的过程。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '辨积菩萨',
    sanskritName: 'Pratibhāna',
    otherNames: ['辨积'],
    category: '菩萨',
    summary: '象征辩才无碍的菩萨。',
    story: '辨积菩萨以无碍辩才著称，能够自在地演说佛法，度化众生。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '宝髻菩萨',
    sanskritName: 'Maṇi-śikhara',
    otherNames: ['宝髻'],
    category: '菩萨',
    summary: '以宝髻为饰的菩萨。',
    story: '宝髻菩萨头顶宝髻，象征着佛法的殊胜庄严。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '普眼菩萨',
    sanskritName: 'Samanta-mukha',
    otherNames: ['普眼'],
    category: '菩萨',
    summary: '以普遍观察之眼照见一切的菩萨。',
    story: '普眼菩萨具有能普遍观察一切法的智慧之眼，不遗漏任何一个众生。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '金网菩萨',
    sanskritName: 'Kāñcana-jāla',
    otherNames: ['金网'],
    category: '菩萨',
    summary: '象征如金网般护持众生的菩萨。',
    story: '金网菩萨的慈悲如同金色的宝网，将众生从苦难中救护出来。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '善财童子',
    sanskritName: 'Sudhana',
    otherNames: ['善财'],
    category: '菩萨',
    summary: '《华严经》中福城长者之子，代表精进求法的典范。',
    story: '善财童子为求正法，参访五十三位善知识，从最初文殊菩萨到最后的普贤菩萨，象征着菩萨道修学的五十三个阶位。他「即身成佛」的精神激励无数修行者。峨眉山被视为善财童子的道场。',
    scripture: '《大方广佛华严经·入法界品》',
    isHot: true,
  },
  {
    name: '龙女',
    sanskritName: 'Nāgakanyā',
    otherNames: ['妙庄严夫人'],
    category: '菩萨',
    summary: '《法华经》中八岁成佛的龙族少女。',
    story: '龙女是娑竭罗龙王之女，年仅八岁，在法华会上听佛说法后，瞬间示现成佛，利益无数众生。龙女成佛的故事说明了众生皆可成佛的道理，打破了修行时间长短和身份贵贱的限制。',
    scripture: '《妙法莲华经·提婆达多品》',
    isHot: false,
  },

  // ==================== 罗汉 ====================
  {
    name: '宾头卢尊者',
    sanskritName: 'Pindola-bharadvāja',
    otherNames: ['宾头卢', '坐鹿罗汉', '宾度罗跋罗堕阇'],
    category: '罗汉',
    summary: '十八罗汉之一，以坐鹿姿态著称，曾显神通度化众生。',
    story: '宾头卢尊者是印度一位外道论师，后皈依佛陀并证得阿罗汉果。传说他因显神通而被佛陀命令不许入涅槃，常住世间利益众生。其坐鹿姿态来源于他曾骑鹿入城度化国王的典故。',
    scripture: '《增一阿含经》《法苑珠林》',
    isHot: true,
  },
  {
    name: '摩诃迦叶尊者',
    sanskritName: 'Mahākāśyapa',
    otherNames: ['大迦叶', '饮光罗汉'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，头陀第一，传承禅宗法脉。',
    story: '摩诃迦叶是佛陀的上首弟子，以修持头陀行著称。他与佛陀在灵山会上「拈花微笑」，成为禅宗起源的公案。佛陀灭度后，迦叶尊者主持了第一次经典结集，功勋卓著。',
    scripture: '《五分律》《阿含经》',
    isHot: true,
  },
  {
    name: '须菩提尊者',
    sanskritName: 'Subhūti',
    otherNames: ['须菩提', '善现'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，解空第一。',
    story: '须菩提是佛陀弟子中「解空第一」者，深悟空性之理。《金刚经》中多处记载须菩提与佛陀关于空性的问答。他象征着般若智慧的核心——「空」。',
    scripture: '《金刚经》《心经》',
    isHot: false,
  },
  {
    name: '舍利弗尊者',
    sanskritName: 'Śāriputta',
    otherNames: ['舍利弗', '舍利子'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，智慧第一。',
    story: '舍利弗是佛陀弟子中「智慧第一」者，与其好友目犍连共同出家修行。他因听闻「诸法从缘起」一偈而悟道出家。舍利弗在佛陀弟子中具有极高地位。',
    scripture: '《阿含经》《大智度论》',
    isHot: false,
  },
  {
    name: '目犍连尊者',
    sanskritName: 'Mahāmaudgalyāyana',
    otherNames: ['目犍连', '大目犍连'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，神通第一。',
    story: '目犍连是佛陀弟子中「神通第一」者，与其好友舍利弗共同出家修行。他曾以神通力救度母亲脱离饿鬼道，后被裸形外道打死，是佛教史上第一位殉教的弟子。',
    scripture: '《阿含经》《盂兰盆经》',
    isHot: false,
  },
  {
    name: '阿那律尊者',
    sanskritName: 'Aniruddha',
    otherNames: ['阿那律', '阿㝹楼陀'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，天眼第一。',
    story: '阿那律是佛陀的堂弟，因精进修行而能在黑暗中见物，被佛陀赞为「天眼第一」。他是《大念处经》的请法者。',
    scripture: '《阿含经》《大念处经》',
    isHot: false,
  },
  {
    name: '富楼那尊者',
    sanskritName: 'Pūrṇa-maitrāyaṇī-putra',
    otherNames: ['富楼那', '满祝子'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，说法第一。',
    story: '富楼那是佛陀弟子中「说法第一」者，他善于随机设教，对不同根器的众生说不同的法。他曾发愿将来成佛后说法度众。',
    scripture: '《阿含经》',
    isHot: false,
  },
  {
    name: '迦旃延尊者',
    sanskritName: 'Mahākātyāyana',
    otherNames: ['迦旃延', '大迦旃延'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，论义第一。',
    story: '迦旃延是佛陀弟子中「论义第一」者，善于分别经义，辩论无碍。他曾度化很多外道。',
    scripture: '《阿含经》《鞞婆沙论》',
    isHot: false,
  },
  {
    name: '优波离尊者',
    sanskritName: 'Upāli',
    otherNames: ['优波离', '优婆离'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，持律第一。',
    story: '优波离是佛陀弟子中「持戒第一」者，原为释迦牟尼佛的理发师，后随佛出家，精通戒律，在第一次经典结集中诵出律藏。',
    scripture: '《五分律》《四分律》',
    isHot: false,
  },
  {
    name: '罗睺罗尊者',
    sanskritName: 'Rāhula',
    otherNames: ['罗睺罗', '罗云'],
    category: '罗汉',
    summary: '释迦牟尼佛的之子，密行第一。',
    story: '罗睺罗是释迦牟尼佛出家前与耶输陀罗所生之子，后随佛出家，成为沙弥。他修行精进，严持戒律，被佛陀赞为「密行第一」。',
    scripture: '《阿含经》《四分律》',
    isHot: false,
  },
  {
    name: '阿难陀尊者',
    sanskritName: 'Ānanda',
    otherNames: ['阿难', '阿难陀', '欢喜'],
    category: '罗汉',
    summary: '释迦牟尼佛十大弟子之一，多闻第一，传承禅宗二祖。',
    story: '阿难是释迦牟尼佛的堂弟，出家后随侍佛陀二十年，因记忆力超群而被称为「多闻第一」。他在第一次经典结集中诵出经藏，被尊为禅宗二祖。阿难在佛陀灭度后证得阿罗汉果。',
    scripture: '《阿含经》《大般若经》',
    isHot: true,
  },
  {
    name: '提婆达多尊者',
    sanskritName: 'Devadatta',
    otherNames: ['提婆达多', '调达'],
    category: '罗汉',
    summary: '释迦牟尼佛的堂兄弟，虽造逆罪但仍是佛弟子。',
    story: '提婆达多是释迦牟尼佛的堂兄弟，出家后曾想取代佛陀位置。他提出「五法」改革，破坏僧团，但最终堕落。提婆达多的故事警示后人因果不爽。',
    scripture: '《阿含经》《法华经》',
    isHot: false,
  },
  {
    name: '周利盘特迦尊者',
    sanskritName: 'Cūḷapanthaka',
    otherNames: ['周利盘特', '盘特', '蛇奴'],
    category: '罗汉',
    summary: '以念诵「扫帚」而悟道的愚笨比丘。',
    story: '周利盘特迦资质愚钝，连一首偈都记不住。后来在佛陀指导下，他专念「扫帚」二字，最终扫净心地，证得阿罗汉果。他的故事说明了只要精进修行，愚笨者也能成道。',
    scripture: '《增一阿含经》',
    isHot: false,
  },
  {
    name: '难陀尊者',
    sanskritName: 'Nanda',
    otherNames: ['难陀'],
    category: '罗汉',
    summary: '释迦牟尼佛的弟弟，音乾达婆王。',
    story: '难陀是释迦牟尼佛同父异母的弟弟，长相庄严，因恋妻不愿出家。后经佛陀教化而出家，证得阿罗汉果。',
    scripture: '《阿含经》',
    isHot: false,
  },
  {
    name: '摩登伽女',
    sanskritName: 'Mātaṅgī',
    otherNames: ['摩登伽'],
    category: '罗汉',
    summary: '由外道女成为阿罗汉的典范。',
    story: '摩登伽女是印度低贱种姓的女子，因恋慕阿难尊者而用咒术困住他。佛陀教化摩登伽女，使她出家并证得阿罗汉果，破除了种姓制度的偏见。',
    scripture: '《阿含经》',
    isHot: false,
  },
  {
    name: '耶输陀罗',
    sanskritName: 'Yaśodharā',
    otherNames: ['耶输陀', '罗睺罗母'],
    category: '罗汉',
    summary: '释迦牟尼佛的俗妻，罗睺罗之母。',
    story: '耶输陀罗是释迦牟尼佛出家前的妻子，以贤淑著称。佛陀成道后，她随摩耶夫人出家为比丘尼，证得阿罗汉果。',
    scripture: '《阿含经》《释迦谱》',
    isHot: false,
  },
  {
    name: '嘎达亚纳尊者',
    sanskritName: 'Gātdhāyana',
    otherNames: ['嘎纳图'],
    category: '罗汉',
    summary: '十八罗汉之嘎纳图。',
    story: '嘎达亚纳为十六罗汉之一，在佛灭后与十六罗汉一起护持佛法。',
    scripture: '《法住记》',
    isHot: false,
  },
  {
    name: '伐那婆斯尊者',
    sanskritName: 'Vanavāsin',
    otherNames: ['伐那波斯'],
    category: '罗汉',
    summary: '十八罗汉之一，梵名伐那婆斯。',
    story: '伐那婆斯尊者为十六罗汉之一，相传在野林中得到很多雨时，其修行如雨声不息。',
    scripture: '《法住记》',
    isHot: false,
  },
  {
    name: '跋陀罗尊者',
    sanskritName: 'Bhadra',
    otherNames: ['贤护'],
    category: '罗汉',
    summary: '十八罗汉之一，梵名跋陀罗。',
    story: '跋陀罗尊者为十六罗汉之一，意思是「贤者」。在佛灭后与其他罗汉一起不入涅槃，常住世间护持正法。',
    scripture: '《法住记》',
    isHot: false,
  },
  {
    name: '苏频陀尊者',
    sanskritName: 'Śubhinda',
    otherNames: ['善宾'],
    category: '罗汉',
    summary: '十八罗汉之一，意为「善知识」。',
    story: '苏频陀尊者是十六罗汉之一，经常手托一座小塔，象征法身常住。苏频陀与随从七百阿罗汉共同护持佛法。',
    scripture: '《法住记》',
    isHot: false,
  },

  // ==================== 护法 ====================
  {
    name: '韦陀菩萨',
    sanskritName: 'Vajrapāṇi',
    otherNames: ['韦陀天', '韦将军', '塞建陀天'],
    category: '护法',
    summary: '佛教著名护法菩萨，统领东胜神洲护法，守护伽蓝。',
    story: '韦陀菩萨是佛教著名护法神，手持金刚杵，守护道场和修行者。相传他曾是印度婆罗门教的战神，后皈依佛教，被佛陀委以护法重任。杭州灵隐寺的韦陀菩萨像最为著名。',
    scripture: '《金光明经》《大随求陀罗尼经》',
    isHot: true,
  },
  {
    name: '伽蓝菩萨',
    sanskritName: 'Saṃgharāja',
    otherNames: ['伽蓝尊者', '伽蓝护法'],
    category: '护法',
    summary: '佛教道场护法神，守护伽蓝（寺院）。',
    story: '伽蓝菩萨是守护佛教道场的护法神，包括美音、梵音、天鼓、叹妙、叹美、摩妙、雷音、师子、妙叹、梵响等二十位护法神。关羽是汉传佛教中最著名的伽蓝菩萨代表。',
    scripture: '《七佛八菩萨所说大陀罗尼经》',
    isHot: true,
  },
  {
    name: '关羽',
    sanskritName: 'Guan Yu',
    otherNames: ['关公', '伽蓝菩萨', '关帝', '关圣帝君'],
    category: '护法',
    summary: '三国名将，被奉为汉传佛教伽蓝菩萨。',
    story: '关羽字云长，三国时期蜀汉名将，以忠义著称。据传关羽在当阳玉泉寺皈依智者大师，被封为伽蓝菩萨。自此以后，关羽成为中国佛教最重要的护法神之一，被尊为「伽蓝护法遍九州」。',
    scripture: '',
    isHot: true,
  },
  {
    name: '增长天王',
    sanskritName: 'Dhrtarāṣṭra',
    otherNames: ['南方增长天王'],
    category: '护法',
    summary: '四大天王之一，守护南瞻部洲，持剑。',
    story: '增长天王是四大天王之一，率诸鸠集茶罗等眷属守护南方南瞻部洲。其形象为青色，持剑，守护风轮，能断一切烦恼，增长善根。',
    scripture: '《金光明经》《妙法莲华经》',
    isHot: false,
  },
  {
    name: '持国天王',
    sanskritName: 'Virūḍhaka',
    otherNames: ['东方持国天王'],
    category: '护法',
    summary: '四大天王之一，守护东胜神洲，持琵琶。',
    story: '持国天王是四大天王之一，率诸乾闼婆等眷属守护东方东胜神洲。其形象为白色，持琵琶，护持国土，令一切善法增长。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '多闻天王',
    sanskritName: 'Vaiśravaṇa',
    otherNames: ['北方多闻天王'],
    category: '护法',
    summary: '四大天王之一，守护北俱芦洲，持伞。',
    story: '多闻天王是四大天王之一，率诸夜叉等眷属守护北方北俱芦洲。其形象为绿色，持伞或宝塔，守护众生，令其听闻正法，财宝丰足。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '广目天王',
    sanskritName: 'Virūpākṣa',
    otherNames: ['西方广目天王'],
    category: '护法',
    summary: '四大天王之一，守护西牛贺洲，持蛇。',
    story: '广目天王是四大天王之一，率诸龙王等眷属守护西方西牛贺洲。其形象为红色，持蛇或赤索，护持众生，监察善恶。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '阎魔罗王',
    sanskritName: 'Yama',
    otherNames: ['阎摩', '阎罗王', '焰摩罗'],
    category: '护法',
    summary: '地狱主，主管幽冥界，审判众生善恶。',
    story: '阎魔罗王是地狱之主，主管地狱道众生，审判亡者生前善恶。据《长阿含经》记载，阎魔罗王主管主命地狱，率领十八狱卒，判决众生所犯之罪。',
    scripture: '《长阿含经》《地藏菩萨本愿经》',
    isHot: false,
  },
  {
    name: '欢喜金刚',
    sanskritName: 'Hevajra',
    otherNames: ['喜金刚', '呼金刚', '呼金刚'],
    category: '护法',
    summary: '密教重要本尊，吨迦罗、金刚无支我等之本体。',
    story: '欢喜金刚是密教重要本尊，吨迦罗二十三位之一，也是金刚乘的主要本尊。其身形为八面十六臂，双身拥抱明妃。其教法主要流行于藏传佛教。',
    scripture: '《喜金刚本续》',
    isHot: false,
  },
  {
    name: '莲花生大士',
    sanskritName: 'Padmasambhāva',
    otherNames: ['莲花生大师', '咕噜仁波切'],
    category: '护法',
    summary: '藏传佛教宁玛派祖师，藏地护法神。',
    story: '莲花生大士原为印度僧人，于八世纪受邀入藏传播佛法，建立西藏第一座寺院桑耶寺。他降伏了西藏本地的神魔，使其立誓护持正法，被尊为藏传佛教宁玛派的开山祖师。',
    scripture: '《莲花生大师本生传》',
    isHot: true,
  },
  {
    name: '大黑天',
    sanskritName: 'Mahākāla',
    otherNames: ['玛哈噶拉', '护法大黑天'],
    category: '护法',
    summary: '藏传佛教重要护法，吨迦罗之一。',
    story: '大黑天是藏传佛教中最重要的护法神之一，具有护民、增益、怀柔等功德。其形象多为身形黑色，怖畏庄严，踏于火焰中。大黑天在清代被奉为护国之神。',
    scripture: '《大黑天经》',
    isHot: false,
  },
  {
    name: '吉祥天女',
    sanskritName: 'Lakṣmī',
    otherNames: ['吉祥天', '功德天女', '财富女神'],
    category: '护法',
    summary: '佛教护法女神，赐予财富与吉祥。',
    story: '吉祥天女是印度教财富女神拉克什米的佛教化现，为佛门护法。据《金光明经》记载，吉祥天女功德无量，能除众生一切衰祸，令得福德智慧。',
    scripture: '《金光明经》《大吉祥天女经》',
    isHot: false,
  },
  {
    name: '金刚亥母',
    sanskritName: 'Vajravārāhī',
    otherNames: ['多吉帕姆', '金刚猪头母'],
    category: '护法',
    summary: '藏传佛教重要女性本尊，胜乐金刚明妃。',
    story: '金刚亥母是藏传佛教重要本尊，为胜乐金刚之明妃，也是转achi(内火)的主要本尊。其形象独特，头侧有一猪面，象征智慧与方便的结合。',
    scripture: '《胜乐金刚本续》',
    isHot: false,
  },
  {
    name: '金刚手菩萨',
    sanskritName: 'Vajrapāṇi',
    otherNames: ['执金刚菩萨', '金刚萨埵'],
    category: '护法',
    summary: '显密重要本尊，象征佛陀大力。',
    story: '金刚手菩萨是显密共同推崇的重要本尊，代表佛陀坚固不坏的智慧之力。他手持金刚杵，能破除一切魔力，护持正法。',
    scripture: '《金刚手经》《大日经》',
    isHot: true,
  },
  {
    name: '那罗延天',
    sanskritName: 'Nārāyaṇa',
    otherNames: ['那罗延', '毗湿奴'],
    category: '护法',
    summary: '佛教护法神，宇宙主宰神之一。',
    story: '那罗延天是印度教毗湿奴的称号之一，后被佛教吸收为护法神。据《金光明经》记载，那罗延天率领眷属守护佛法。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '辩才天女',
    sanskritName: 'Sarasvatī',
    otherNames: ['妙音天女', '辩才天'],
    category: '护法',
    summary: '智慧与辩才女神，赐予智慧和学问。',
    story: '辩才天女是印度教智慧女神萨拉斯瓦蒂的佛教化现。她掌管智慧、辩才、音乐和艺术，是学者和学生信仰的对象。修持辩才天女法可以增长智慧和辩才。',
    scripture: '《大吉祥天女经》《金光明经》',
    isHot: false,
  },
  {
    name: '功德天女',
    sanskritName: 'Siddhāyatri',
    otherNames: ['吉祥天女', '功德天'],
    category: '护法',
    summary: '施与众生功德的福神。',
    story: '功德天女与吉祥天女实为同一本尊的不同显现，她能施与众生各种功德利益，令众生所求满愿。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '摩利支天',
    sanskritName: 'Mārīci',
    otherNames: ['摩利支佛母', '阳焰天'],
    category: '护法',
    summary: '具有隐形能力的护法神。',
    story: '摩利支天是具有隐形能力的护法神，传说能救一切众生一切难。关于摩利支天的典故很多，尤其在道教和佛教中都有重要地位。其咒语据说可以隐形，令人不能见。',
    scripture: '《摩利支天经》',
    isHot: false,
  },
  {
    name: '坚牢地神',
    sanskritName: 'Prthivi',
    otherNames: ['地天', '地神天'],
    category: '护法',
    summary: '主管大地的护法神。',
    story: '坚牢地神是主管大地的护法神，于《金光明经》中记载其为佛陀证明，说一切树木药物皆在地上生长。供养地天可以得谷物丰收、资财丰足。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '散脂大将',
    sanskritName: 'Saṃjñāyaka',
    otherNames: ['散脂', '散脂神将'],
    category: '护法',
    summary: '北方多闻天王的眷属，管辖一切修罗。',
    story: '散脂大将是北方多闻天王的八大眷属之首，统领二十八部药叉大将，管辖一切修罗道众生，能调伏一切障碍正法的魔力。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '巨智天',
    sanskritName: 'Mahāprajñāpati',
    otherNames: ['大智慧天', '摩诃波阇波提'],
    category: '护法',
    summary: '释迦牟尼佛的养母，佛教中重要女性护法。',
    story: '巨智天是释迦牟尼佛养母，也是佛陀的姨妈波阇波提的称名之一。她出家为比丘尼后，证得阿罗汉果，护持正法。',
    scripture: '《阿含经》',
    isHot: false,
  },
  {
    name: '紧那罗王',
    sanskritName: 'Kiṃnara',
    otherNames: ['紧那罗', '歌神'],
    category: '护法',
    summary: '佛教音乐神，人非人之一。',
    story: '紧那罗是佛教中的人非人之一，长有人的身体但头似马（或似某种鸟），善于歌舞，是帝释天的乐神。在佛教艺术中常作飞天形象。',
    scripture: '《华严经》《阿含经》',
    isHot: false,
  },
  {
    name: '摩睺罗伽',
    sanskritName: 'Mahoraga',
    otherNames: ['大蟒神', '地龙'],
    category: '护法',
    summary: '佛教护法神，大腹行之神。',
    story: '摩睺罗伽是佛教中的大蟒神，属于八部众之一。虽然形象看似愚笨，但实际上是具有大智慧的护法神，能守护佛法，利益众生。',
    scripture: '《华严经》《阿含经》',
    isHot: false,
  },
  {
    name: '频斯色天子',
    sanskritName: 'Prajñapti-devā',
    otherNames: ['频婆色天子'],
    category: '护法',
    summary: '色界天子护法。',
    story: '频斯色天子是天界护法神，守护三界，令众生不遭苦难。其名号代表智慧的出现。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '紫微大帝',
    sanskritName: 'Zǐwēi',
    otherNames: ['中天教主'],
    category: '护法',
    summary: '道教神，被佛教吸收为护法。',
    story: '紫微大帝是道教重要神祇，后被佛教吸收为护法神，主管天界星辰，能护持修行者的命数。',
    scripture: '',
    isHot: false,
  },
  {
    name: '真达罗大将',
    sanskritName: 'Canda',
    otherNames: ['真达罗'],
    category: '护法',
    summary: '四大天王之一眷属。',
    story: '真达罗大将是增长天王八大眷属之一，能摧碎一切障碍。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '招杜罗大将',
    sanskritName: 'Dhana',
    otherNames: ['招杜罗'],
    category: '护法',
    summary: '四大天王之一眷属。',
    story: '招杜罗大将是增长天王八大眷属之一，意为「执严」。能护持众生远离苦难。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '毗德罗大将',
    sanskritName: 'Vidhūra',
    otherNames: ['毗德罗'],
    category: '护法',
    summary: '四大天王之一眷属。',
    story: '毗德罗大将是增长天王八大眷属之一，能护持正法，调伏魔军。',
    scripture: '《金光明经》',
    isHot: false,
  },
  {
    name: '宫毗罗大将',
    sanskritName: 'Kuṇda',
    otherNames: ['宫毗罗'],
    category: '护法',
    summary: '四大天王之一眷属。',
    story: '宫毗罗大将是增长天王八大眷属之一，能破一切邪见。',
    scripture: '《金光明经》',
    isHot: false,
  },

  // ==================== 其他 ====================
  {
    name: '金刚',
    sanskritName: 'Vajra',
    otherNames: ['执金刚', '金刚萨埵'],
    category: '其他',
    summary: '佛教护法神，手持金刚杵。',
    story: '金刚是佛教重要护法，手持金刚杵，象征坚固不坏的智慧，能破除一切烦恼魔军。金刚手菩萨即为金刚的代表。',
    scripture: '《金刚经》《大日经》',
    isHot: false,
  },
  {
    name: '力士',
    sanskritName: 'Yaksha',
    otherNames: ['夜叉', '药叉'],
    category: '其他',
    summary: '佛教护法神众。',
    story: '夜叉是佛教八部众之一，有善恶之分。护持佛法的夜叉为善夜叉，能护持正法。四大天王各统领二十八部药叉将。',
    scripture: '《阿含经》《金光明经》',
    isHot: false,
  },
  {
    name: '阿修罗',
    sanskritName: 'Asura',
    otherNames: ['修罗', '阿修罗王'],
    category: '其他',
    summary: '六道众生之一，常与帝释天战斗。',
    story: '阿修罗是六道众生之一，有天人之福而无天人之德，常与帝释天战斗。据《阿含经》记载，阿修罗王曾与帝释天大战，后被佛陀教化皈依正法。',
    scripture: '《阿含经》《愣严经》',
    isHot: false,
  },
  {
    name: '紧那罗',
    sanskritName: 'Kiṃnara',
    otherNames: ['人非人', '舞神'],
    category: '其他',
    summary: '八部众之一，主管音乐的神。',
    story: '紧那罗是八部众之一，长相类人但非人，善于演奏音乐，是帝释天的乐神。紧那罗王能以妙音利益众生。',
    scripture: '《华严经》',
    isHot: false,
  },
  {
    name: '乾达婆',
    sanskritName: 'Gandharva',
    otherNames: ['香神', '乐神'],
    category: '其他',
    summary: '八部众之一，天界乐神。',
    story: '乾达婆是八部众之一，以香为食，主管天界音乐。他们以美妙的音乐供养佛陀，是佛教艺术中飞天形象的重要来源之一。',
    scripture: '《阿含经》《华严经》',
    isHot: false,
  },
  {
    name: '帝释天',
    sanskritName: 'Śakra',
    otherNames: ['释提桓因', '因陀罗', '天帝'],
    category: '其他',
    summary: '欲界第二天忉利天之主。',
    story: '帝释天是忉利天之主，统领三十三天，是佛教重要护法。据《阿含经》记载，帝释天曾多次请佛说法，护持正法。其前世因听闻佛法而出家修行，后感得王位。',
    scripture: '《阿含经》《金光明经》',
    isHot: false,
  },
  {
    name: '梵天',
    sanskritName: 'Brahmā',
    otherNames: ['大梵天王', '梵天王'],
    category: '其他',
    summary: '色界初禅天之主。',
    story: '梵天是色界初禅天之主，有大梵天、梵辅天、梵众天等。梵天曾请佛说法，是佛教重要护法之一。',
    scripture: '《阿含经》《华严经》',
    isHot: false,
  },
  {
    name: '大梵天王',
    sanskritName: 'Mahābrahmā',
    otherNames: ['大梵天'],
    category: '其他',
    summary: '色界初禅天最高统治者。',
    story: '大梵天王是色界初禅天的最高统治者，据说此世界即为其创造。他曾请佛说法，护持正法。',
    scripture: '《阿含经》',
    isHot: false,
  },
  {
    name: '摩酰首罗天',
    sanskritName: 'Maheśvara',
    otherNames: ['大自在天', '湿婆'],
    category: '其他',
    summary: '印度教神祇，被佛教吸收为护法。',
    story: '摩酰首罗天即印度教的湿婆神，后被佛教吸收为护法神。在密教中，摩酰首罗天被视为大日如来的化身。',
    scripture: '《华严经》《大日经》',
    isHot: false,
  },
  {
    name: '那伽',
    sanskritName: 'Nāga',
    otherNames: ['龙族', '娜迦'],
    category: '其他',
    summary: '八部众之一，主管水域的龙族。',
    story: '那伽是八部众之一，即龙族，主管水域。佛陀曾多次降伏恶龙，使其皈依正法。龙树菩萨即与龙族有深厚因缘。',
    scripture: '《阿含经》《华严经》',
    isHot: false,
  },
  {
    name: '金翅鸟',
    sanskritName: 'Garuda',
    otherNames: ['迦楼罗', '大鹏金翅鸟'],
    category: '其他',
    summary: '八部众之一，以龙为食的鸟王。',
    story: '金翅鸟是八部众之一，巨型鸟类，以龙为食。其翅膀展开可达三百三十六由旬，能遮蔽太阳。金翅鸟皈依佛陀后成为护法。',
    scripture: '《阿含经》《华严经》',
    isHot: false,
  },
  {
    name: '优婆离',
    sanskritName: 'Upāli',
    otherNames: ['刀杖子'],
    category: '其他',
    summary: '佛陀弟子，持律第一。',
    story: '优婆离是佛陀弟子中持律第一者，原为理发师，后随佛出家，精通戒律，在第一次经典结集中诵出律藏。',
    scripture: '《五分律》',
    isHot: false,
  },
]

async function main() {
  console.log('Start seeding...')

  for (const char of characters) {
    await prisma.character.upsert({
      where: { name: char.name },
      update: {
        sanskritName: char.sanskritName,
        otherNames: JSON.stringify(char.otherNames || []),
        category: char.category,
        summary: char.summary,
        story: char.story || null,
        scripture: char.scripture || null,
        imageUrl: char.imageUrl || null,
        isHot: char.isHot || false,
        status: 'approved',
      },
      create: {
        name: char.name,
        sanskritName: char.sanskritName,
        otherNames: JSON.stringify(char.otherNames || []),
        category: char.category,
        summary: char.summary,
        story: char.story || null,
        scripture: char.scripture || null,
        imageUrl: char.imageUrl || null,
        isHot: char.isHot || false,
        status: 'approved',
      },
    })
  }

  console.log(`Seeding finished. Inserted ${characters.length} characters.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
